apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:cbkUYybzRyv/4fEHNQ5+6vZxh/IoeqPNJ8w1AsL/0U33FmWdIrKZPw==,iv:+wZuyfDtfVo/K2DHHHnAAjK5AqLxZubscgaWu19U1wg=,tag:5K/0WqeIoy8RJCXKxvEH8g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3azBxMGV4QTVCakdqMkJK
            Q1Y2YWk1bk80UjlGb0gyaGUxM1hRalkxUG1jCk40aFgyNUZjSEplT0lZM0I4bm10
            RmVLQjB5aU5wSmVkUHBaRUpPZGNWNWsKLS0tIDZIT1Mxb2thVGlPbmZxbTRuWEha
            NVlkdEVMTnpNLzNCTTBSQmo2aFdwTFUKu/BzCQbTjEgDtGKVOGQjqsCMIvcXYCrs
            50oRhBUSRwHxNfePIgZjnXi1eyMVfC4/zpDf2Ow9PvpxyIpGjE1HQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T23:56:16Z"
    mac: ENC[AES256_GCM,data:DXA+4f6XLPuD2bOSzGf2bbndEx5u63SELXm4CweUDSthC0qtq7IcpXi0pW0xon/TEG1VRfmYtZx7WCZq4tPuQiHWGGvivcI3ofhhaNTbxc3F7jlSJg3+vJ6YDI3OWOH7VnE21+TjvvkXNnw57lO4z7kSuD62YeLOK4WzjOFXqdA=,iv:pyUDszT2EhwoCG3Fjl+z49Z34mQ/6YbmUAvGYE0y+L8=,tag:RP4UgUTLq0jUwlGggX4yog==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
