apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:EyOanUC//AYSyO3HdTXn2IXorL9isHADSfgM8BmKaI56ZgqFdYpdhQ==,iv:jy0j5l0FQr31r3lN+CWu3Oh6lm8ceWHhMJ9Yg4y6sEo=,tag:uvUjGxHUzpXn1agaOJII2A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSDBEM0ZaSEVuZXBKd2dH
            S3hmQmJvUW9IczhKVVdmS2tSNWN0Vm1KY1drCnNDczFWaHJaSUVVUlNHM09od1Jw
            SmVKdUVUdEcySlZzSERMSE5JeUgyajgKLS0tIHRmakErbkI2dDFrWDdyVFZsdFlu
            RUxncGxjVFBVTk14Y3lzcktsSUJWU2cKkO3WQlyzwdZ6KlVKpYHIfDiiB1dgj4sF
            RSWz9EXwQZv6/e0+/JlnXezqcBSfea5fypF0IQMETV5YdnHWQ8wd4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T23:26:10Z"
    mac: ENC[AES256_GCM,data:NgS4dEDXFUL7hfUCsW42BdG8FMyOSjxX1M425ixzs5UIii0g99UJ60KLqL5SWxBwBQe6UpyLvS8JAVpdEz4IjpyhqCahanKXDmEPM/CTjhJpXo58V7dVDMTpBAG5iWO5KxAhwuri9iZ8RvsJA6HKFCuNFO/kX9XxwoPW2dPUBcM=,iv:F1/zG2Wo57xWywvw8Fvic0a+RmWskV001yFMyVbtXPE=,tag:5JbL3JYYgmV8V4uwlCDjzQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
