apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:q0HX7r8t+UFw5CRweiatJmJiYfcb4mxfp9AJcgNAPSupqvfzpDdywg==,iv:P8PQ2wW5bXrHqHbM/ktx/hEZFJKVCLFTz1doMiWORqk=,tag:NIsL1RTzdkOgFnDXZePQuA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjc3BxN1RlVDhYWmw1WWVq
            TjNGSDFFZ1B3cEQxZG1yQjVRMEppMVVtSkJBCnRlQ2s4c1hEZkhvbitZUUpvUUph
            Vm5tcFhaanNzc2FWejFISlF0Q0hFVW8KLS0tICtJMk1CcnFqc3lWcmVOZnl2dnph
            Nkk4RFdEOW5LYUdWb2xTWk5pZnZIRWcKQE9BTdzc5568q6wuI+v2dWlZZlpMW46a
            gSo+spcTqEJIIrhU9BxH64Gt9OOR5ntl41bOVt0jGMkhkptEKh8RCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T03:39:41Z"
    mac: ENC[AES256_GCM,data:42XFmvSwkGFdHPEu+0858quLgx6YU0V4Fx58BfIg0xpQUEeYPEoRrbfdN/WaCDs95QSTz7IcG+AJQkvvhay72fUU7CTcT2swkAMjtCqkLVyBhEiMwe164JHF5O3apPC2NbFuvbnXiPUI6aPlmQZx8RylBcXBmwOJqT/WVuRnGLk=,iv:bG/iZikVBcVwM6I8q7wkWojT3vHkSRzZKiEADLw4atA=,tag:JlAl6j8E+VxxE//CpI1K+w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
