apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:spNg/kdJpShfeyRxe9Vf6NbZsk8Yv+MGs79y3Z0h0TnVSvCqCWjrfA==,iv:KiYgV6ysxChkcEfkXeOQT/Qyp0+UntvLsF9bLa1nZR0=,tag:1ES7POOeLdc6ARfvqKsyOg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYVhkM1hscEE1OWlmajRs
            QlNIMkhYQTR1NkcvaFpaSTNoVFBGRnExN1hzCjB0TXQxTW8wa2JJb0pxcmpyUGlZ
            MGNxYWFLT0ttQTR1Q1BJcEJLdEttYjQKLS0tIEVkZnFvaE1XeUhkYzY3Q2o4MWY0
            bkFZT0UzOXBvRW95QllmM0FlbE1wRUkKxCVMWnwG+9jAHleQIb2RRCTCJvKf70Ow
            ns36eUAgwR4OULTa7eSaq40xDWbE7TaG40ktyeAC0P397whuTa7W5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T01:46:41Z"
    mac: ENC[AES256_GCM,data:W33GAB+y8c1hbMNvDHbV9sf4yZyaD3JsitrqB4f03BMDK+2eqfNIr85ybfIlkF1vPu6YrgJ4UPZTkpkxYLSPoyxOLNFcKPJEAbzE1N/d61pGn6QsRK2MAFM330Row5ECDVbxJ5ow8NtWSmm3jFIMKPk6gaDdFQzW6s4YWboKUcw=,iv:a0ZGNvhWWKgBqY5POSAFF+qINd9E1Jl77vdae9QjhOg=,tag:yisOfk0MsQAnxKTJznnlYQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
