apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:yeSmrKJBse4Xz+atQd40SPTOH+ALoxl0GK02RSxYh0rfZ4LrcBx0+A==,iv:rj4iklggibj/zDHdy19eBk4N5uWULjmqn+gsrDOUtBg=,tag:6Ts9ZCsPBB34GA3MXfDDug==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMTdmSGlQbzd2U2xobElU
            c2J6UlV0TVZIQ2NmK3ZKSXpWUWNIdlVVTEMwCnM3RW4vOGl0TTBjK0t4NXZDRnZU
            QzRGSHc5VkRhVmNrQkNMZFE3OHhBbUUKLS0tIHlnR3pxOERSY3VsNGxhYnZ5RERY
            dGp2NlZzUDNTdEJac0pCNmlZN3ZvdjgKwpZh0jCoM1ozW388E68mrurVGW//tE5Z
            rbsL3tbPCkDkY3AijOoJc8Digi6vQPbnin36rZKXNXQFhV9/aOiNdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T21:34:49Z"
    mac: ENC[AES256_GCM,data:FFhjIgyDqiMsr7DKkDgTCAOJZzyPFQ8iHsd5wqxc05yz8bbK+UIkbqJoiYcX7Fj1GizLDrrHzoBRxRrg4WM/wfWZYcBKlGw3na/yNlqP22MNI2BtYJCThkkN6gAAiEY3cjyqZ8YxLQeEFgsCA057eWYUaa/g+my82oksA0xGu38=,iv:IEMFdG9Z72ZRsJsolu01RjGX5vDd0k7yj40A+o3KHvQ=,tag:K8Qks6vybcpDx3QKA8JVWg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
