apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:tvkUEW9DRtRgA6I3Uw6zxVMkCK+OA8AprMfIbN2tHjy8GXS0gjHzKw==,iv:KTtfeNGS2/inaG8LKF57tekWuOe8MqCiHdCsQgACc9U=,tag:9APGS3ChHT7FnoXYKXtixw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUmFGOUpJWFlWWSt5Wncw
            QTBtRmxkK3J3bHRKeDRDNnFmNzIrY0hMTlZrCnJOMnM3czYrNm1BSFc4bUkzNzB6
            YVlyWEhyNGJOQUFwK2RacmN6eVNSbzgKLS0tIDRBYzFUc1c5K21EWG1lR3JyNHE4
            N1grcU9iVTc1UCtaT2NCNmd0cXRWbmsKCN2nF4sPD96sd/hD8sjMjA4lyHoeliV3
            2l8edAyBiLFnpesmgt/q2sGC2jHlfuvhgmrBsV+rcVJ19s2hfNyKEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T05:24:07Z"
    mac: ENC[AES256_GCM,data:Il6Cy3p+V3K13D4/3Tl5/E5cCRFWc15pFx2EIZ2cijKdtQYhSlU/kqGOXkFqCuqs8/eTQgk7+XZhPRAeVVsjwE7RQmeF/+RBrYA8in/RkIkc2TvoSwT/3VZAQenC0vRu4BbYMXukcB6wOf2Hc1DRzWJYKoKq6c7+GbeqjKSK5NI=,iv:mYveUhz/dFKBWKdkB4RMphmM+3ra70lwDgx35LBaTMk=,tag:+ijqyRF1b5exJe9hrcLyqQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
