apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:RztWfNsM8yclCwpVvUX911zeyIlROZ59SuRpuHZrmkQ6UaSVboLFhw==,iv:zA/zdct4Wp8pAu3tXV/vWB6OAotY+6veYIjCPwzip5U=,tag:OApdkadMcQ4mr8DJghIcjQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUlg4VW52elNhelFCenpC
            R2gvN1dsWjFLZDQ1MHBHaitBblRnVVFOK0dnCkxKMUpsK21XanUyY2lyK3A3RDdP
            UXZZaEJwS0VYRlZQUktPakgvN29OQ1kKLS0tIFZmOUs4dGVUb29GUCtCcmZoc1o4
            YWhXQ2FUcGJ6bUxOT2RPWG9reHoyK00KZzCumFOyA5QEMm26+/MFooAaiQJ+8MHE
            VQToc9vH7uEOjbkfuyiZ0npIixVJ3TWkX/JwiZ5p/43BS/pRg0Of4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T15:49:57Z"
    mac: ENC[AES256_GCM,data:alz1N0X3xoYeAV+ux8R7gsQOiBHV8CjvRpcqdD29iiPokzqSvpC78MpDhLHfErjto4PBcZFoXYZMilHh4uvNzTs2XLczWoxcICpikRaGYL+W5CigS+qeDg/8rkMyiB4TwUAJLNfVwXLv7wUafT3tGq0A+T6wXvpPMVEVPTucHm0=,iv:6A3JvidwZPaq7R+zpro9UueayIe/bttr9RBVPHo1RDw=,tag:eG2F05JiNxCk0KA+yMX5Vg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
