apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:24nuYBMIISDz+SXZprY0RNLE+oYxQvMGendOMAvoi9Y1feg40HBDZw==,iv:7VRhCQR4qcoDgAXARNritcCGDJly9EsYs0u271T+HSs=,tag:ad8MyWzSIrFIRYt9e/ht3Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbVY0a2xWMlNlSy85ZS9j
            Y0NmaDBUNjRHSHpybjV2d1BxTFoxNXo4MXk0CmJVcEUwYzYwb3Z3OFUvSHprdGRH
            RUI2c3BSRTJiaityUEZsN3EweGh1bWsKLS0tIFc4TlVTb3lNTWJaK214VFUyaTk0
            UkJVeTV5dk41eFYzSTBMMEp6RHVlQzgK5a36nuGJDRCAwFIWHq1Ulk2TpXBdLlVK
            IANWXrBR4Ni1fN/0VzkBIh9CZNjGfmQfdfHCKCrwq8kiWcjfMJWFCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T05:12:30Z"
    mac: ENC[AES256_GCM,data:AbOo3TsbrHd2L7asK6ISJEF9R+LgfcauSs95Kd5xE4e5dCMKg6p+hTTOND9MN89TXQQsHC0sKa6CbpkS5l4pVQLwyvyFrM6GbvNAIEePUJZz4IbVU5WRMaB3F7+Qpd/c+kC8mUcBxZtgAilm7Au8N2A5F2WHKFpJkP3D4KplHjc=,iv:5hII58pbWVh6+gGWuB5/IDPI/6TjF6ROYxHnG+WeWHM=,tag:wrE8Thl5NtcrpVsYo1CvUw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
