apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:K0qvkssjDVdHe9cc7IJCE9yIpJZHCR0g7rkeis6Q5ZDSTdbitaygLw==,iv:7a40HG3guPFbpM2utVaO+sS+o+a0bdjEVoVRcpnSYRU=,tag:SF9/cyfbMTDOvZ/oeri+ig==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWelE4YTAwU2NaYnNINnhu
            cWdMR0NGend0SFhVN0xhTXJPdUo1U0p3U21RCnYzRTF5WnBJR1RYTDJCK2Ird0lE
            d1JNQ1EyVDNCM1BjaVdJemVkQkxnSFUKLS0tIGVjd0dTanlBM1FGWjZDQWhMcWh3
            Z2pkQXh3bGVCQXAzb2c3Sm9iMmYzNUkK2BTFTL2EUZdMpPvnCZiD5vWOzQ1U2PhB
            w3AweexEqPLQe4ebxKm4/aaLYT3kdPrTNmp74BcotywOZ6afCL1ybw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T18:56:19Z"
    mac: ENC[AES256_GCM,data:cdZGoxQcGDTGJkJZY7BDa0pg+RZUwfkjeGPE0BTJiPw4j/Df+OlzRA581Zv/I0dq0jHrowdIlJLTvy2KdYachogrFTQA9o/lfKxIysppWjwyBvAeI4ZqL3amS8jBrY8Bapt4ue6shBQ0U+8r0hQin6xV0CnwjPhwas9DMrG1+rc=,iv:JCqKKcGZxTfzzmbsznIv7hR54lqG2iCkQ2z4lxTA58M=,tag:3EB04T/LFI4cy0pUTQND/w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
