apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:SDWUViunZkSVLaY+3HCtqzagcjbsxa4TbzT/QG/h4rWmIzQ1Ydqmvg==,iv:FYkfzAFwZI460mp+LognaYNwW8zvevrcrQ8mMTYGU8k=,tag:vf4xkdaBK9IqK6WEAtDX1g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZnY4T0RwWHc3LzRkYWFW
            VUU1UWNNZkVOamFaWmRoNFQ5SG5MZTh3c0RBCmd1RytBNFI0YmNrV3ZNc28wQnJm
            S09MRmFFZkRyUW1mMVNidVc4M0VzVXcKLS0tIGRPZDZXVE5YbWYzSTM3VzZZUmNP
            YjhpbXRrMEttYlJ0NFlnaFBJd3pCNEUKO4hafUL8b9aoL2tPTjKTTCdijVZdsnru
            iMe+Rgf81H5EnlXbK3XfBkwo5fdAt0bjuBXiuo43QbCrgItwSt/b1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T19:54:50Z"
    mac: ENC[AES256_GCM,data:OsoaKHXCj8u2Msf/Cdc1GAew6E1VjOfmfxcOkzpNFqhuaTq+gb/AHh8llmg60OY8EGBS2vNqJdi7KqnOhiJ9AON5rbRyC00WVhmsZkNROCbAkctiF0BqvpWMvxEbXwuiAw6ZAgXUANDzQnJAzrKLanJaly2jMtO7oJ7+p9vrQ0o=,iv:soxCFunCz1BX30IaFMw/gE7/tAYKzmB76aIuCCeQfTo=,tag:meRGkHIig2hTxOowoP5Daw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
