apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:4M/hS53eP+MbFARv0nSofGyKRwRmSJtvDx0WkqyrdzflbW9wHvxe7Q==,iv:uU5NM43qmwGc79AA3TOx1sRqxXzDeYe5EBGCp6HOtPQ=,tag:X4o9CyfLQ9duXVTA3Q8PBQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WFhMa2tKQURaWCttaUJB
            MzY4YUhjL1AyeVpmTzFpRjBxN2g2T1lvTTFnCjI0KzhHNHNxOUhsZjBjbGRzSjVL
            TEdFdWhuSFJtSHhiV0xqOVB3R1NpMmsKLS0tIGdVQ3ZpMHhPY0xIVU5zRmdPS1NF
            MUc5NEQwalF1RlhwbnJvZzdWakE5NlkKHu6wZfjwdKtqdSZa1aP3JDsv2p4ztnIL
            /zG+Ky1z1LGdKHkbSvhjSbRihlNSjhqnCdyTHfyiacuEyh4sudSEZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T20:26:03Z"
    mac: ENC[AES256_GCM,data:58BJVarjWblkiAoH3yL5ih+aoG5XqTl2VAKnpPERt8efPKDZVwq1cQgsgB/6TdkjhLvxiiIYcHGC2ba0bQHOYqaNlF8I/LnUgF66betY0R3A2MVLBO+O764yaxPgn7HboXJ8+98Gyk0k4gS7cTMclBpZDtMhb7k5j+UiUAgZ6qI=,iv:aWaUwxbxDPMX4a0TFDHzFVVsTsj0pP6jO9xqCdkQYEo=,tag:ezoIGKHsL6pCQGGM680EGw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
