apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ufzbGKOAL1Pqaa8fEbtErkhVRD6qcwMup0nEJ0xsuEGHAgExas8MeA==,iv:myRudNTNY5d2FohOwHQWMbsRTGf4MBmERgG6xLEGY3k=,tag:gkDQU+uDOZfIycwBPnkv9g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZldlMG5sRnJFQ2ttZFFK
            d2JqNThzcEhuTjI2REx5K21LbTQwQ1VIdkdvCm56b29qSHFSWGN4MkpiSmdOUmlK
            MlVNVllSNytQRGFIYk5pK1Q2R2IrRDQKLS0tIGwxSlE4b2tkbW4xdC9DZDg1VU5U
            dVFiN0wrdk1tbVdNMmxGS3FoeG43cm8K649X9i6C0qf/fnmGJqR2F2hHkWspbT+B
            qh1YT4Rzfp7q68lji5SuNI0IbmE3sUFyYX4s+LxNHOSv37Sf1nXPoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T02:10:19Z"
    mac: ENC[AES256_GCM,data:vTMBfSqkqWt7lAaeEJPqd0fGQLFGhet36PK02lFqsqXavH1OmTXJ63aIkETGrlr+UmJDZTwMHD7tyy+MKImghNz6hMl1UUPzug8gV2/beSDPfEBEcCRl+Z+BcvqPCp1HASA4qe/PQCukDplD0k3X3sYYN0IMCveOME3YmSjyyJs=,iv:WXSYDzRpcRj7R4ZgqmyPmJzY68qLEw/aQj0gWFy9oyM=,tag:/birTPqFnjH2D0gGcmDdhQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
