apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:PxXvXBZGbqGTpU8Dm0+s7sRtuHD/PY0j3rE0s/MhzDoQYfhajK9fqA==,iv:GJm96c570/k72pArT9OVwUnLkYiFzubviSiQl0m74Bg=,tag:Cs1xu4aUJsiMKNrdZVfa4A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5OTY3VktXWmJJN3IwRUhK
            ME9XcmcvRU9iUjg4VmFVbnFhQlFnbEczdEZZCm9MejlrZUdIcUZ0S0djWHljUlpC
            WVhuOWx6c3plSTR4eXRCekJ6Q21LLzAKLS0tIGxnSU5DbVhyZk4wL1Foam9LVEU0
            bnp1VVFkSnRtQ1F6Y0hZdGpKTTF3Sk0KbhmGMvxY9GR4U8plaGCtN0qZclp2X1gP
            BIvcdIm3qD/BpC+62+FSkUVekV6DBADlAHTk9/nDKH/zoxMw6xn9gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T21:53:12Z"
    mac: ENC[AES256_GCM,data:4eonc7rTYEf3GAGtn7g7J8rse8IEia42CgaIjEBuVGrSq63EMzJB93mhDE8ugIK1m0r1yK9G6dyvzB2QVQF3Etr6D0HcPPcdud1FjdaE9wCz4siLUsbOp9o4DsjQJYQsFI+TTq4G8rxS/4qGS9oU72bU0ZfAorCg5BxdCxmDz/Q=,iv:TGMyo3TEAsYtSJvb7AGCokjNdriwLMPsswQ6KpGoh/g=,tag:p5tPXWuQsCNBl+4rlYIdkA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
