apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:sp35NfMRNwkUdqdc9/OqPNOP6/aOPvRmXevaEueQhldMFwPoE5AG3Q==,iv:6mxe0C4QQNOpeLkQul/Z4Ugx6SLzyTTKb6GsYNrBP7g=,tag:s1UiDPTKcWGUR/ystuNBVQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYN09OYkRkbjYvbUNrNzRy
            NVkzQVErOWNOcU96cFpmdE5SK2l5aUNYMWowCmJYRGR3cXdVVUwxUTMyZ1RPR3RG
            R3hzN3o0cmpsMlRqZzlxMWRtdVNQNTgKLS0tIDNSbm9sZkc5THlDZENGdkdqdFVt
            OTg4dTFsSXFlTWpyUWFpTGE5VHgwaVEKOEi0ugdts3+A453APNbTSpICt29TFRNa
            zn1Zwi8ftoHFI+t6uaj6DESVnYrKcgLmckL5HuPm/04reTCUVtfC/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T20:28:59Z"
    mac: ENC[AES256_GCM,data:HIWms5uz/VsLuNw6U8pyguq1kwlSBwiMNbq0d1CCG2sAP/h4tgCvUN8xUdM3x6Sox3MNP3rBQRFuDbahp0iIL5pqWsrSH6+RyNJ/mVO8O2mRkm30NoKVFvaW/fn9cLwV51de7aiC3W3XPOtF6d8BOnAPyAhE0J9D5wgV6/IHJw0=,iv:SVdYb4I/0KUwYn8h5s34LD37bra7H1wTgMhrDBg62dg=,tag:vW50zUlB0FDzBpLBb7vWCQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
