apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:UN8qcWe0rXqUYJ+gatz1BZgfXN7WBAVjM5haRm4DC0bC3FI7UVfPeg==,iv:/C3lVPeaoIKTXrrTQWJFKobfqNzIK5xHOaHHN3Vk/E0=,tag:XCbTC1FWbfItkxomBa+CrQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbHZ6VmhPb2t3RVZFT29u
            c083TzFYOTdwSnN2VVpyUnhOVU1tNE5iL1RRCk5rNGxWNjdKelY0UmpDRlVGNEUv
            ZVpNdVJKc1NMWUxaaUFaR3lzRlJLdUUKLS0tIHdLMnNCWStyemJaZWdjVFFnbkFh
            TzEwSHhuVG5rVG1kdHNNSUZCODJlRjQKMI9EpPUuOBoJ1pq4lQ0ph4sMgVvyCkeh
            UX9HLi6jHNteiCn5vdsHiAj2RcpYowQxx6zdaLfv2tNOKO5xH6l3Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T06:43:34Z"
    mac: ENC[AES256_GCM,data:SGqObdYvH0HSEsq0oSzG1RLeIAyU554QcYmm3pnbBFq5h48vkqNYf69U6u8PsRuO9AhLwXhnumcRlcJ/SiEU2ttD2PwnHCoaTAVF6sXp2ecZYnNaRL7YzxMxDl/8WnHtDLppVZQYBUjxOVDF4b0ltp6nnpA+XixP3ViK0w/+k3M=,iv:+UqPcmKVYGJUeS5RwJI7mK9xjxdLU6jh5NpAcf2vIds=,tag:rw9ZWKRaML8Fsudt+kPmGQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
