apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:9/G/9F6UUAydjDj9IJFPRLh5Z5Xo94SAohKq+cYgMlp2y3L+kGEB2w==,iv:nO6QFe00PShveJLvckp/ouEnqCUH/bWd60QSlorbfq4=,tag:XGzIhEAK0OJALgQ35HnI1A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcmpwUmxEZDlzVUM3d3VX
            cVA3SjhzR21jU0d0U3VUNS9MMjdCVXZHUzNrCmI2VTdhaTRPeVloWm5nSUFpTmNU
            RDFjM01LdG16R2ZSNU5DODBtNXovS0kKLS0tIEo2Y1liZzFOUm9MQ1RMS0tKOTgy
            KytFK1dKeUp1NmhPYVVKYi9VcmcwNUEKsiu/fNi5s3pkrzWC5X7kHzr2eqpTLgUU
            rRCzMGDdr96xYyougubrOex9A35wZRuyx4T57mmxZFCFVqlqzcs32g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T20:56:36Z"
    mac: ENC[AES256_GCM,data:34uc31apVzmwoLaJNaODl+0/muuI2bUJCjPpdL+bXbinRt68hXGdc+yKuZSU/+twIVOwJpMokATmwofWX6biCgYWgX7cpcMANwqfGzjYv+JwdG1kHpL5tvr2HKiyLa151xtRksTiEIZ4eoI13q+G+/l7KWayzk6fdcErG52y9sk=,iv:T1x0fmBN/yIb8H9z6s74tMlqF6S7ioQ/0jIQ0fqOA2c=,tag:CU0odKw4Xk2Qo4mtLGdggA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
