apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:b3Yk18g1R8mV/MOVGIyS4oHy+99y1foGlesyX1nhcxI3AmlAAiiRx7Qsobd9MmDtbNPdoA1iomdbQvUV2xT4oQnzuvbbhHiMtsInt47X0WcG+n+XfW6kRBCF1Q8s,iv:eGkWHBvHFkbzvu00UVyKvhiQ+nUQ3AxO+gmSdpGCANw=,tag:s/d7I8/pvkF+oW2jre+Bvw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWTFWdjJWUGFBWHpoTEJT
            N0Rzam1aMk8vSmFwblhMMnhHN2tDTVNqQUFjClhGeGVlZkNXSmR2dTZ0R3ptNlpG
            WXlmVVdKdzYwRmVXZ3JVSDZxUUxHZVUKLS0tIFFzL2gxYTAzU2tUcURnc09MNmVw
            cHlYSFhxanZKbUh2anBDSm4xK0g2R1EKkm2YCnuTh4Net2B6RUz1D3sipAC9imgw
            3mgBdlkheXtUyf/Lvs/0nH97G1p12ZOv+N7H754uKJ4EO8GdfxG6eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T15:49:57Z"
    mac: ENC[AES256_GCM,data:JmSaaDj/990d0NH3oXqCIOYQIRB+fvn311csPi9yfi1e86wD9xVxTLHEJE5/+j9arEt+LlTovx23cwo8gitvQoQIgfTYuyGL76R49O7iBXQwwJ2fe8ch+xhe93ifKSI82a9pEkkLjjGUmAvXRowKEaG4QT5nVL6kV1TIQsjH5/4=,iv:yM0rHgwWBBWz2IxkTsiY2mKx0dE6HQynlbMQtU1/BQI=,tag:0DVwnWji4j8A+sRHW2IXrA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
