apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:L/vfgRbAISZ8TfjX4ktzZzeWQOQDfjE0vIClRMSqYas2yN5GJlykHsMC1M2MxSkdg810xPAlwJGa291tTB/6Hf/Lnme1wYzwP0B7CLTHuXdQjC+jXaSJLqwk+fq1,iv:eY+BybDhV+Dv5ljKXz7nx1lb8RWVwyTNOcs0S6wiz3k=,tag:zN3S06VDFAO7jn0AjSWvaQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNHdiUFBWbytld0lSRTlo
            YmtpbUNSc0wxYkdIV0tWWTNZbVMrM1B4ano4CjYyWWdkV3VWd2FVZkNmdE9yWFZx
            Ty92NVFPWWFEeSsrZS95Tm1IY3pYeDgKLS0tIEpKa2xLQXBnUjZIYzJCOEZjRUk4
            YUVHSzFJaGpWTXV1b25IRTVDbmNyYkUKbq80PQB6+8j5dAT583aoGK2j8ZCeo8Hb
            Ioenh+1rvJXS/m0SAh+KLE6XbBFtIHQVMnlD1lSOVrqP7xcxoNz1pQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T20:56:36Z"
    mac: ENC[AES256_GCM,data:oH7HTW9XQGxpdkAar4oYcpyil/DbJEZ7RFW38faQN+VJOm4iTo+qAJSGOplHhAQ5kG9n7jwQZ7fpkeD+ZXz4CQmA5vRcfu0b0mRuN9cw7AAY4/6QlO/VJQZAXMRrk1ShiS0wZoZGm3uslDJNFtsmLS66V6hnRcy+8d5JYZ0d/WU=,iv:wh5Cq0EssIIJISQqE01pAS5RRW+HwKd1A1+jMwU8oYw=,tag:t1PRnR6vYStVMRWv27YH0Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
