apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:/zq5bDRffeSizkklELMncVH8/20HctRao96kVEhZmddS4hOU/I0LsEnRVYH4JX4IskNg+zQX48OEt4ORSC9WxWL6oYYGN0g0pxL7bA1DyI8AbgGHvNgZMVQNzoS5,iv:LO8E/3GI6xbfkq3TjHGVqsdYUA5L77sf3J2wdY6n/KQ=,tag:V3gCi0YNEhZwrpJ5wfwjuw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRFg4bWg2Zm1jaDV5M2h4
            QkoveGdabFVxVkk1LzBNUHBLMWttNmo2NEQ4CnhMME5QaXFVbjZlS2tOelJIL0ZR
            ejJwZSsxaC9hU1ZONXNhWW50akxBU0kKLS0tIG0xRDNQNkJLRStzd1VjZVdpRmpU
            a1FDWFdJb3BrS1dtWURGTnhyTlVZN0EK5JQRqArdCU7/oACygUZ+onpxsQLtUKSc
            VKylIAn/Rgaizzv99i3CEPkfALoU/3/Kkc90HEb6moc/w66dssIwMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T20:28:59Z"
    mac: ENC[AES256_GCM,data:uDAAg9J4vsu8QZPxctz3JiGWzT/qcGiyDPjjhMXFAGCoH2d7g1B82dajeZkfzmmelktnTSzOCmo68ds0fHBtRwvheWWappWWvoX31Cl+GwxQ1p4djjZ3kwfT2k31W/hG7dd6qbuLg2u+xs3l3uip4dru6R4SBpTEp0Y1rj4IquA=,iv:DHLJDCigziqYIqDkXbBnN95e7uneE/VA+RAreQ5AXus=,tag:YfgXXRAjRaIUT1L3Bzfohg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
