apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:M9TFNAhHlnFYl7uCJakC4quNjWbgSW2386rUCj17u8jaNGia9nCWoP2QJaIe5kijBqd6QY0RL8zaA17hD2vkl2yUVQzvLgSZgEV+a947Sq0UQM4INpsv2KvT0awa,iv:NsHLqnaNCc+xkbSpZWsRaBibYJP8BTDgAmCt3uC1LHw=,tag:zftzYd49uaVzLfRaPu1o2Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUW9tWG5xMGdXK0NTOWhs
            WXlXMVcyUEplMnZxK0t6cUdiRVZaOENVL1E0CmtzWWdVeGoyR1MvU0FaL01vdkFa
            ODZZS0QzWlNpYitnd0NERWUxNXFPY2MKLS0tIGIydSt5K0hQejFjQlNaRFVzMUJp
            VC80RStQdU52eHNjdzJzMC80WHFteWcKanOao2aXgdspQTBH/GjsHSuQMrytPPVD
            kzJsHIek8ISJmNEU4Bk0mlMVQieK45BU2TiKdOT4R8W848LObsuPxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T01:46:41Z"
    mac: ENC[AES256_GCM,data:EOOfZSmDeHmQsKEHz3y0qtm1pPSPDuJavI/iQUTDMDqnxjes01uYf2/A97ysKNQZaW2l03UyuQ7WlMlUISb+wyNnQohWySPEs9S7iTuasSbpAUVTjKrLt94LPRMSSNTSl+xvEDUC+tBYaqc1rgv1/WrTITrDW3CZE6Pw0DCAprE=,iv:qfqBf5DuA3z1yUYOFHEsZuOsANBq5KwBf+dSxCPT1rs=,tag:PuNtTrsZG8pdPpxQe3DuoQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
