apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:VlJKHdc25n4Uub1VSZeLc4LkwO/0msU0DRdsss0JL+tLxOlbL09C/whKYV44DvCpXSN0UzURafUSqqF+ipmvlCp7s3XMdYepK5K73ErjzeV+9EewTKVOHop3tKYq,iv:6qxTEc5R+fR8Kcw3e8Nrb8stgSWVUlXs0gCA2FsB1wA=,tag:gWjnywyLNVRE3QVkwaleZg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZDdRbEtLaHVaWEpOcjBN
            bGorVUdRblRKOGxBUzhOR21LTFlaN2ZIRlNvCldZaFJIQ0FnKzFlWDVHZ3dMZ2VE
            QVRLOUNpOEFncjU0dWc3Z0lxRDhmdXcKLS0tIGJKUWJhd3k3MUZ5MVE2NHpxVlRq
            SEFIdUZJSERCMUZBR242cnZ4NGs0YXcKlTWEoNabq0CR6VFoW9qFsxY/+kLXsdei
            Hs7ez2yLGWdoSIszRLtG73zpDPN8UDdDBudtHadqrK6zCGsVAPFAtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T02:10:19Z"
    mac: ENC[AES256_GCM,data:0uTFR7Eh4nXB7lw7EiP+vaxYLKPwUEYm1d6eiJOaOUiB+7IHDDZ3Aml03tvPGALy/TScpY/OHVs4oSnmOrez7vYzC3yIXGer0VBcS8XCA3Y6NLTMjMeM6NDSfLxtNXceGKFNTNwKn/FrAyXIWJAtjlpj3EogowfnZmputQKY0bQ=,iv:ErxakXqO+fTLnf/pW9zjnW+cEGAtYlPNsnjRNA04sUA=,tag:KDOL0N+0Xod7jXu+F6Wb7Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
