apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:GN4vdV5SqAoiVzCRxNEWTiC/CoVfMPvG9PfYgNo9nyOuSpSWUXxbcd0o/ePTArRT1SqZ4LG2rz4ftk1QGTYQUoMuKDIUcU8yiUW5c0tuetAXAwGDV9qCcrkV6w3Y,iv:87UfaeWcjOu8M1CFGTl/xhn5cxIpcHceb6ttfor+f64=,tag:JGJW6Hqdevlz5NYDUdMjPg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacC9qMHlGaWJBdmt6aEQ0
            T0ZCM1JvSzI1VGhDWVJsT20walJhMzRBdEUwClRDdStvRDNXclh2eGErVHJtTlo5
            V2N3WEVUWmVQSzJ0bmhvdG95YmY2NlUKLS0tIHFncWliL0IwZGVMUkthVXJUZlUv
            aUVZM1YyNlVkQy9NckhlUlhGbWFnSG8Ky5Xf8ENeBWYRKL5aXYwnzB9vftwmGP/k
            qQO/j9ojBT9pTsOVMs37P4ObjFE2xo0bVrMN8mb+6f2xqohcMOR1ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T21:34:49Z"
    mac: ENC[AES256_GCM,data:18e2kByXRaOQCHnG+y1ITFMd+2raMLrRSYeXbuTg4Wwj9PLw/dCqaHrmK8/oG0MNdZ55a82MqgleyPwFsav7eAzp2znrnnqrdBXfwFTzKGXRVSXd29ZzxsVmgQHXcA9l/AHeaj37CIt2oNHucRGSRyBz5ZQfEMVqxsCjCD7YiU0=,iv:ZDxJ0JRm8cJvjx5mbD+D6yHPzoimbPKaMk8Lpz93Wqw=,tag:SedEYDwl1MM8UqCT23n/PA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
