apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:VljM1zI/6LqU0isIRsKEDc54b0NgqLnkSaEv+xXljmGdJaiSMSAbKrxORgQzpCBB0pygTgju8wElHaiSJDSY3wDPeGAdtazpsXgH7ah/oFwRQNxkKzNPCYk8YHFj,iv:X2YaUINszTGymicxta0ezDEVmXcHw3dmalwqB2kDg5o=,tag:Yk9KGMmiieUbe40s57yNMg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicW9RTFFsZVlnbjdSeEEv
            S0FNeUFxZ3VDWnZkSlFId2l5M1VYMXlSZUJrCnRJbFMxSmIyY1F1Tmp2SmllRjhv
            Y2NCRUJjTXNORlo0T2RlODVDbnl5VFEKLS0tIDdSSDA1b3JIbStKeTRpN2xWdkE0
            NjEwSmsxaUJHVkxlKzlON01XUmcrK2MK2WlEqrbJsWKCm7cK2EZYDzQq/CoHeRHy
            e8+O9THLCkoTfEX6ki1mapGRBtQAOUXjE1yDrpSPEw9c+Tl0HS68nQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T05:12:30Z"
    mac: ENC[AES256_GCM,data:nzYKjS7BQxmP42ySHoqe9IfSBrMqFxyXDOdWi4Q349JX5jbLZK9/ubWIf4/hSjoB20s3CT+wxSt7rQ/Sl/1QRcEvLxbi4UrrhtN2dmAt8lpzri76rxGAAlsb2wy7Z9Wuo5irivhORMdFDzGFwccn3DskZlU9RveE1V/rSNGZY+M=,iv:LHpKeEDGA1gaagT/t9rhVd/KO/+Ff9QSIwIn67WRMWs=,tag:7q7pLlCVP/IFf2qMDf+NgQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
