apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:MmzWKMdznPQ4B4oTyBjtZTMIPuVsqhyMaHOpyqdmyjvK/aGUQmxdsWPg7+pOoEqT8N2b5vdXGNZ5PAjf4lzfoZKJBUCcy2rkqOwMabUIfUrLNwqgj1Ptsw4f8poE,iv:ghwIENZw69OAZEpEy6uEQndYbWabbhNZPmE8zaMNw9s=,tag:jY96lT1zGvc/mcq+OHBBqQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNWxpM2xGeEwrREhoRCtD
            aXd0aFBLOGxNcS9HT2FUTW1qSSt2TEpCSXdzCk11dmZLS2V3Q2tsQlJkN3pjR3lt
            SElrS1hWZ1VOVFF1bmRKdjZlNFliMDQKLS0tIHhCTFhudkVnSUs0QVVhVDBKeGNB
            L1pLTHBIbUpsOEp3cTB1OWdSQzlnQzgKXcjHmHzxZxllKtSbjsdRmEHF47pt4I31
            gXm+8gP8e5v2kbCrhtPvFkeyQnVvpidSYkKzLthlz19EfsujBuN6SQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T23:56:16Z"
    mac: ENC[AES256_GCM,data:MRibysYU8QNwm+4wQghhG+NY18Dx7WClm62RS5sgfTOGgtJ6vzqJXXjHCxxvXVpx+sL9/jeHvKhWND+dSx7tOjgR5MBwPoih/SQ4JpGc6MR7cffwxUU2zuDwZCJnGURgWHpPaW49on8tD10qpzlvvPobZHQ5hK6fe1mKG8Dtue8=,iv:0DJWKbcUatHOHoWjwDTKr91cDppfePwDhFC9+VjSE18=,tag:kdvHE4YPHkBCn5qrxFrLJw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
