apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Ff+7JbQd+Z3WvUrmtVIRCL/3SmYmjF+y8c0sFGltHw8MlBUFmY2S04rQOw+kPQaptXB0K+sQU+fRBVD1NsnCPTlMq1CboGW5yi9maQLziujpDfbuaviimil2LhZi,iv:D0a5IptZZwMLBvSubB5TBLMLKPYKz5V5g3THOtinKLU=,tag:Doads72MYRIPGZwhJHaCyw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveDVNQTNsZTdMd1M3elhL
            UXJ0QkpQVkF5ZDU5bURhR3pxOUMvTW1JcmpBCkp2MnhYekY5dUs3UTZBZk1RZnIv
            UHJUWlN3Y0hHSmhhcVNVc2ZFd2FGVGsKLS0tIGRFRXFkUEtKaE94bHZNSFlCZ2JR
            OGh3SmxOUk1RcEZhYjBQWEpPNjFYek0KUr6qeRH1q5nitx6CATHVIoYAmMKd3XjI
            mP4xgg7cW81N6KEhWhIy+EAr9rqCMuF5Epg7RPhMQRfmXUgDlO5j0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T18:56:19Z"
    mac: ENC[AES256_GCM,data:lnVsSN9fm0LMfVsAJma24oribHOEO+hOWMNLs+002VAq/7NunEoOGpMHaF/a8nouiCj4TZ+jrXMS4shLH3jiyFD7VpEB51pSA7P90mj7v2RmAwKa+iDcfwCDUTDKAM/iMd9b0WDJWwd6UAagDc7g/1iAShaTmE6F/WDMpqC6COI=,iv:HozOQcPP9RAUSiSPjU/FLYUpzm+04yQThNywBygoYn8=,tag:cEeopD6Z/lAkzwe3W6YoHA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
