apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:8wXDt6tQKvgIvXd0iGC1rR34Rgcw5NKvdBAjASpEDv0+FjnohSduO1vHXCr30aFbdHtPQj4crDSDKCiO5wU184juFwFCWob+fieRaNw9Gs+4Em9N1fGbbKtIPLHO,iv:VgEOWJFMob+j468AUa9KtkQyFgs4TmnH093f0w8V/nQ=,tag:8yHUtFOnra1t4qE4uegrZw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkeWxXaTZXbUxrS3VUTnFU
            aWNZaGlEMzFqZzl0emtvbEVPR3k4VWp1SERzCndZTk5pVzB2V3ZkVXllT1l0dzQ4
            RjRINExKWFZOMHNFMHdGTlRnUlR0OFUKLS0tIGlxN2NoeVFsRllad0NkTm82RFVs
            VDlrNGh3dXJLN3g3cWFRUzZlcFF0TkEKeitRcXPEIxrS4e+3RVnG7M075oIDcqPp
            Sch/6nX8IFCo+Wb9Y3FEPSsoVMNXbgaVas2uNliJvFZfEPJ2Yr1DQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T23:26:10Z"
    mac: ENC[AES256_GCM,data:e9IrpZth9eEQ0qCLhXxi3miyPXJOyo6c9XUA+LX5oqwYFsjTo7BkYXDiIwxFBXZjXnCYZk2u0x+SUukQR+1g8XQVGKAa4IoftrEKdDA6BRtbqLbVeM4/7W3MbUGaZkdG1AyvixjazT3HWHx57R2NM0U79exY94vFmiPIXOJGy9U=,iv:EHmHhkxdbwjxh2Vy9XdEFtzwIfzgRNhut0gl4u7nOg8=,tag:itqAfp3KLbdyvj+2zk8SbQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
