apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ydHCc/fgIom7U3fClD4aWTkGSeoYrxQBOr46AXXTrj2wPKBquTDankeNYzB2eB0RnqkxbDephYtLKUs7/4MihdjFTsRJF0MMsyyduq3Z/vqLVuvKd+j8c2z3/noG,iv:TeRpcx2OCz1j8uU5j8N6n4yfjZnf6wZ7C4YvoovB1IA=,tag:JMfVP6WREfN8kTqfKWzeLg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdE9GblRpUXhMMzVRQS9D
            UFlFdzJiNEd4WjZLa1pxemhoc3RIbUtEMEQwCkJIWUF1bENwU2VlN1dhOVhOUzRU
            cTl5THB3amVETjZrMlVabG9EbndNRm8KLS0tIGhOVCtMMExMeG5qOWtIUHovWEYr
            K09HaWVPQnU2SEFUV0MvcDRqbThTQnMKFf/Yl67QOpqSNC/369zQxP/jSXMY26Xl
            TrOmIAk/7UuEMgA02wLQUNfTwxWhpdn/LJU0mhn6/4BUF4Xa/h8vMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T19:54:50Z"
    mac: ENC[AES256_GCM,data:gbkdq/rQxCYwcFgdByFG5AzErKTeha+pj3nDJ9ZVUiobQKGkr2FTY9cdj6yFkWZw8OTL94TKgqk3MhM7aKhhUqKFYnJdoZrqntAfwh31/HSQ/Xap+CibCVuntPxLAk35RWPDR6UcXn5IFNUujxxXbZwI5CoM+W6THq/7sxvDD6Y=,iv:0NXZlqJn57Bq9BhYAS2e02zBZMwTebAiTQimLGFGcPg=,tag:zon0azueI22I03arbSAOCQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
