apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Tkezd60PcFXwkjBkw7/9pB/J8DkAaJP+sAc/Gj4KCN91s2gl0gjsiA+r7XVNEFKAMEZXEfVnUXWHHOknkHZ3cXNEIIKYVJ7rcmXbSD+7G11T09SetklUgk+1Oe9/,iv:x94g0DYMJ95DOzpuf3SjSBmNcnULjz9P/ksq2o31GAg=,tag:sKxob/+TztTaTBR75YOoZg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVkhmSXc0S295QmkwYUdh
            dzdZcndqMndGeGsyUGVQNWNLKzRIWjNvelI0Cmdaa29ZeExXQzdCSmZzcWtQQ1dh
            WEN4bUZiektET1VReDRZMUZRNWxRRU0KLS0tIHNHbm5HR002c1hPMmo1cGFSMXh2
            UWMvdE5TazIxMUNZRFpRVGF1VDdNTmsKwJ5SSydBRbEuIsmf/TM1opgiIuB0phiI
            aEIYviQkkNdGs5ybquFYicOOO649TiO1nC96VpzMIvxiNz6JuVTKBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T03:39:41Z"
    mac: ENC[AES256_GCM,data:YozKb0m2zuBpclWyaZQ90uIsEw2jLwKpYtGgxk1My+lPCcXB06Em6v1G02ufyGRxPD3mea+mxNNJUsgmg9NjUglu4Zx7oAU82rNxxctW6104ypJqyMBcJEeRG3dkSPmJnrVBRVy8ohaz8OS1UnhQ82ERB/fNdNO6oHzga9U1d2I=,iv:+/n2Bj8gUfAwCujzv5/FL70ScxqSmsbrxm9E2MDYR7g=,tag:KQegp/cAjCWQy9+SBTJVdQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
