apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:hHFqu92DT+DLSPIqSwgwKBMl2VYH8dXd6EsII3E1p0e6E4tHz8FJ2DOb/+FDlOiJ+cDnOPITYhwqjyoWi246q1blos5q5dpNrF/hBbcY1+BJlWyaWLK+Axz+S35w,iv:Roq8EZ219XpPFSXPecFruOwmstm0WKeKq5aT5XAPrGg=,tag:v2/nXoCPtN851g7ZJp5M3g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVHI0U0JSZGVPNWI4SkZX
            ZGRHRm5VYlR4YjFvQTJrSHNabGQzbFNiR1c4CjJJZFBHME9jK1FiN3o1SFV5aWh1
            Ykl5RGF3Q2xVNWR6THk0TmZ6TXJyWjAKLS0tIHlhNHJpQld1SFI1MXh0cHNyVTg0
            cVFhQ1BmemE2WjdLNTB5NTIxRmZLMjgK5BMy77ApBvU6px5I1hjiTyW+Ry9QSgv5
            6+7/oym2uJbQtJsAtlN1dYMNSzQh9g2w6pIanKpAX07k7xWgfSy6KA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T05:24:07Z"
    mac: ENC[AES256_GCM,data:X8M1CJ4f3b5wy0atjrvhzWPRzO+RrzY0hTZsLcCoL25IliHMZCiCTgDH1t/m81T2r69GC2xGWG3QVAyQ1LDZTSBCak//epXi79GRY+0mrKKXupl0rkD0WCZxSjAjIkus855qBMtCOOIRpgrpHvIiOXjw4zjjwX0a8m8/SQaeqOY=,iv:W8sj3sM+7S5i9xsLl9vIi5l9msmhapoX1r1Djz1E3bA=,tag:Vmx03a3NdY68MqXk0rbYLg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
