apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Gam/uchZsRNRK+Y9vGzqW2+uCAjjITNVPCFTKKsx5ppLLsei8rKbVxWz9gNp3CDOufkz6Y8abJbQjJQANJIIyu5j4JxcwaBKynuALj6nDJDTD0KooiKkCOZiP+O7,iv:oFc9gexk0LcZFcl1lbhOal4mD3EBpkHFsO5Af2O6paU=,tag:wPKzxl/qls09JppoacA9YQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VUlCS0JGMkhtVkFPemIw
            WkQxTDYvNGIxcXZZQnZ0Mndkejl0Z2ZsV1JvCmc3ajJoem5IVmhZRElteG9PSnhD
            WHQwY3YyckZpQVNrcmJOSkV1Q01xU1EKLS0tIHlLL2x3VGtBV3ovOVl5amY0ZkNW
            U3JFWStKcjViZVJ5YUFMMUxsZ0RmZFUKQh6AZ5t6T4hNjjIlx0iMz6KlK9NLvXj6
            fSbeqsIJ3nFP9mF8UNieCLiOUsqqnlRpA+SwrTbItAf2PbBjPCgx/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T20:26:03Z"
    mac: ENC[AES256_GCM,data:/mReSH3rTo7404nCrriOFzfXlHyQOLeHVQxlxjCcllvAz+zWmm60WI12pFe8O2WEz1g5oMoQoCwydU+Okqfj37p/fbgf/j/giNiiQATxbjYMYwWb1xnO2ufk0M/cdmjhvKdotoxE//UxxY+0Mz1HmA+gzTGlX2Sa3r+1W3GYwG0=,iv:ARNCrh32FEAaHCj4reNNjhuZ5faOe2g59EFBr6aejVA=,tag:W2Sk+zgt7mFBOAOnOAbwZw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
