apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:52QSuDmy65mHER3oKOYtcjkYzzrmLiqN7TjYVVoz0y4WJZKy3oZcg5kvoEZtBIBP9j7oB5zYXM9Zx9dA2P5/dJMoGiR6Z4DG8CVnd7+n0tWQ/nT11yAVlzzgC1sB,iv:L9pHMK14mOn9+5tJ+uic+IfHvmz+uyHmhhgwup7qcS4=,tag:TdYjAxFzUHpKslkICF8aPA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dklVTENYTUt1ZzlJSWdi
            NC9qS0xCSHJoVDB6bEl5cFpVU2xSNjRoclRjCmt3Qzg0bkYvMmxBOGZNUmw4TUFM
            blNHK25waXlkbGMxbjNxTDlEMGZTNEEKLS0tIEJHb0pZYXFEdWFHOWQyelRjVENv
            c0wrOEFEQmFpWXFmbHhPWFFVekxvdncKwbZslIhnYdrNPCoqDqKO/rKp8SkTu99E
            SQKEm0/3clE+T9bUjK5PkgBfgLh6lt3k19Pej8tXnwx8AUbiHdYBzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T06:43:34Z"
    mac: ENC[AES256_GCM,data:3uHd4PxYm2ErSSM9PPIDMeJkkcYZnct/RaK8v8MfKV5YiZFD4h0qpXmoTJVjy+jkg5tRQvVpQ+lx8OGfblOZ1d0wt2i7G7izQPK6Q9sZuVxmXC2tMGbrTldg41p0PzXCjSu8H0VzsCDEyPrYc0T4tqoSCozXVFueV55kudqrdbM=,iv:Y0RmRyp6j8K+S/yuu2CPb/1sqey4Pj1liDjwTtYqgAo=,tag:MZMgU2x+SbDFXz6MyLqquA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
