apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:VmU5NraAHE+FU9QBbGp8bgo+czQSDIxAl9cHUcbYDL9FasPqqKqNTJIz9MLVNsPQljQtL1RyyoDGxSWijXA9Zv4tbqNScZosWzlatPAYx+DS8nO1jR9qFy8DC48PxXnnbWCQ3v11as+pI+UfkXlKhRjND7BSZLsrM1Sahik0lQUH/SYM2W9F4w3uaee9RSh147InZS8qFkX4pfHoBjH4rx7hakmeM9QTM3p8oikR1609aqMPy3tV43Oc2Wu9NC7ioYxp9r/l5RH0uweIyKx5xAlanTYn8g6CLoOFfJCRuC9vrlDYQZJ9aC749OgEudpf6BVcNYvk6S1mUbUXL31EP/l/dsF/QOxm0ms+8ptdJ9gK0eD8HEf8YG9pzImqtcyR,iv:QyZ94RBs43rOnQ1MRuyhKfMtyzXIJKL+T8Mdq3gu9z4=,tag:ksG2xB4CbIWhSg7tXIM9KA==,type:str]
    identity.pub: ENC[AES256_GCM,data:EIw80I6521sMWgVZKmMnFAq6ydElTfKH7DW3oG4lmrAoRSOflshkMyVisq2J3F/Sk6Q3fhk1zalRL08gp1zPaOTGoLdRYDiVo0ryiqCUYpMGtC/sg/4CJrWbLAr0yRLyB57lVqs7ca/MC6wLlZBwAYvb4hh/Z77S4xcaYbXSbUcSflGrm+wGTHraE+rGMP36Uc+f1B0+t75mPzBOfvE8Jt72sCoKeaZYT7zHud+Ie6+DelQ4GQ0W+EKRcoDXIr6RNrUyrefzM6Vgoik8Iw==,iv:9/BB9tiCpusKrWbvrHfPWMIO6pIMkhfrrvg9dtf5tLo=,tag:+aO4HC1eWjmcoPkjXGjN2Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:jCeye2KXR6P6qosUs432mVE7N1p2wxfG+agVCRSVUnmpXDqUMyEP06p1k7zTgiN8mbAM0zL4vufSHu9tlAxSuFFN9JtHsIufIdDyY0HA1oRtvKia9CUkaiIkcn1+7/kwJb1jMrW8Zu6ml26kfSquct8RbO2nsqimZW3KmGJcQYJT+AUgcteaY+zkRWfdhK6D3oLb60XIpuDqChmkO+gGxzaLtN7CaOQCq0xu,iv:z9dc6wd30n5i3+LlP/gslFprIpTTX5rfoMQXCxrfdNg=,tag:PCmYsw/kkh0GgoZfSFWRTg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdjFKRXFCSmlsMDdHVC9s
            L1lkV0hGT1hiUDRGbGloS0RlOEVNeXdWOVJBCm5ZSng2a2lnSU42U1dWZ3FjTFFw
            bGVoeWFDeEJwcXFNZkd2dXY0OU9DaUEKLS0tIDBVdTRaK3A3bERWbXRYc05aQW1P
            MUNFU1BpYVgwU1RUczg0aHJDcXdzYXMKlb9euLRW0Bdfkszg0T9+Vm90XBVvw4E1
            VnH+ZQD0+3ZPLMRmgYvfN/XppBRYadjtCIGW9Dcb0vO16mpusI6Z8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T02:37:48Z"
    mac: ENC[AES256_GCM,data:ajdXm9m9z+gqfwIDkT+pNBimTiKli2KuWjWdae/3lHovugZ5VuS2ZAAOQCifSaPbOLEDodzJRPdadVrHIUlSoTOg5tcjQk5yQjrt0Ajcgo4HWxY551QYqNIzWhJZDvVG76ERxVdRjoA6KwJlHkVRGF9uBFnhIur61hJCUn0kUbk=,iv:cvYZKGMZUuVdBzmOoLmP5givyJIzJh7NDa5W7SS/gq8=,tag:inEpcv+AOYAyrp3vP1l+Rg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
