apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:WRLOhVx9illsbqwl0Oli1IqC1XfE8+1TRsNEdYwLRlInceMY1SPO+89HlrQ7gCC4HiHaM/UZsjDDQVkrE+P30dIdpgaea21r4SmW70FAne+/zE0BrhE+kB4PEHW/5/Ynx3bZdzGIzEcCIcCEUKEai30u8einQXLIpcHRKIuKn9c4MDRuO9TogrzorsotYugpK9/vzs/n2WrRbo3JsQCmNG8g+lUVz2Jc/0v67Mmc3VWty6hu68Sde8QF+P6oTccrbwcGTZxwob1/7Btng+2MgoTmlvdPTOF/OPamxY2XuTPZyyt1i5p0ttuoCeBZbzbdfwXHdUvvF//vKoEy2GyqHUKGGy3uDNFeDL/rPMIrDC7Yvn2XdYtEI6zc/h+IyYlo,iv:Rfls+FyBIHuSs/V+eU8rnzWhnXcViStmMQ/WVElYItk=,tag:J7UizGd4I87vtnRDo0dvig==,type:str]
    identity.pub: ENC[AES256_GCM,data:zJd9fkg0PAx5zG6QhwfVDdtALBBi7q7DS9im6GMh1dZauo5WC+lonpbFCZn+8np1LRS7Bi9qqs0eihKwzsXFIzdwnSyrwjMRHUFv88jBDVqszZZFbal1EtP8HRPta72NzTxUXTQqyl4lKglwGdSONR+miENNSDxW7DktIY4LEZvY5MS+hDr0TmH7rEgLpg8xUpB0OubP9FprOmGZ39INmZo/ModschVlQBf5+aBXtwIOAUCaBnyFZv5yyrrESj4OKffi1OwcXYG7SLd2Kg==,iv:j54qv++Bv20JIm85eTG4YhoplUuas/fpSYQ0BDTO0ZA=,tag:UAyq0FpKsnI7BTFjRgOSyQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:+5sL2qrvI8RRiAF0xFD83jP9zfdPYMhavVtklL27Afw7eh0ClFkqjR+pDWoNc4tRo6LbbvbaxXyEwIKuMoyBAfV12EuqDaxPAttEe1OutN7mlCkMyTRBW/Y9OAyRPb4oEQluP/qgKF0koZh+Bm8f1qYnle09m/1qGj2ZVnxfi4bbwBi60r5TXAUS5y4wlx3aFfFQJfvowc1CLndmJVpEawOZpU8Vx6vA8G9T,iv:ysTzm1WPq2YaSifYZxcNtZbSGTYjgjUOx7/qMG7gl3k=,tag:gt2ZHzCb9deFD7RkxA+KHg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUU1xdzNhQU1Yd1F5b1g2
            c2RTM2xFMTgwQ1dyQ1VFRHROUmFIL1J5Q3pJClN3cVZRKzdxbmI5NzNvd0VRQXM5
            VnJZVUVUSE1vUi9ORHpNWmxDMHFlM0EKLS0tIEVoN0NDWWNXUy9xRnBRbG55amF4
            Y2ZuUDRhRFkwYjRkUlAvTmxvTzZpZXMKVDMQ4lxGDNGoWvqX2+/RHDdsQIVS2t3e
            kF/EcFmTuGtdPAemJ+RQqZ5GMjB+Q7h09hGLC7m6oHiAAwO4h/xNUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T02:29:36Z"
    mac: ENC[AES256_GCM,data:j6u/+IdWmHdTiFVbO07AzAFrIfKWSbHXevklqSLoDAiPrtWaB+qFC0qU1ThcP1H4jBr1tu1iCM18we9sjRcUnFjZo61eW1dodZ/mKbxbluoy1Ghv6MkochzfKg+ADlM0eo27rMiCaW8isKVWmElLPB+J+EtH5Lw5u+H3mpEQ370=,iv:/78HE//amrhAF61O2H8iNwC0CFw95o7LQ9KLa8tjzAU=,tag:kQ4fCg3DO4IUs0TQdkDIPA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
