apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:y/6B1TS5ADy0jTetkEx/psqHrziq7weZPA4dNZ/TEe8t9+Mf4i9+AwcsQ0gOx3GC8twJ6sBjzYrTjsVSjAAHoAnJnMOefa1g8aY/X2VRhp3RpOWUjV4NBU2KU8Eg3bi/VpscYxkaqVlDnEVEeIRhPQAMKIadWkHy4tElsGXG/RETUh8XGPzN1B1MktTVfLmsfYkdXqehhQtoVadLyk0vjsl7O+sMzpbfsEk2fnF+j4/amWJWUvlKTsnkfKcSm9He9OlaUkpLIi28Jw2oC8BKM2dHgGpw2S0KoZbJCMjQy67bJCyRcjljwOJZ+fYlsMk5KO6IG8ue/Ib07RJT/YAFPl4VUR9TMm9dtI1daH7Pd0GIYoSlZdbRBZpeSuOwDlX9,iv:APp81GDx75Rj7GYUe5ojWEL5eMmY7Xcabd29ZCsLfc0=,tag:6wBCiVldADkvBef1dX00VA==,type:str]
    identity.pub: ENC[AES256_GCM,data:xP+k5Xd7Dgx7JiqvJgLmaul6Oc+MYUvHUAyNkbJExbFyse23M83Xski602dKC6NCtOZ1dML43Ud4ZUlOhklY4yBg4zZI7oTXa9CEi4cbaIX7SnKZdHHVutoIx8bWBW90R2DVzHZsJEF5pUHQ4rQpETQ+S9GmkPhHPfIF4DiT359bz79fSHz7gJR5GwqOPZlvzaTM/LfoiW8Ng71m1Pdu14oInzr9yqHpxV5RRirTYuYbzN+qHr7hfbqb6ZeIpT0LFiwyq7jYW0lH2oRRyA==,iv:2wClmHNlO3wjK1vbthrY6AceWK+wFvBSeBq0O2U63eM=,tag:B54v4W4nVnw4pbPqwP/6QA==,type:str]
    known_hosts: ENC[AES256_GCM,data:lbJYNhu10N9fh3Y+alR1YdNn7YR/69irc5N/Jtiht3NjZy3uB6Qvjo9oHHj5C40XiseUj+7nfjromnlIM4RfBPqlhwIrGhcpOg0y+nhoSZAgjK74vbEHc7p9LryD9aIIbR6FNHoFK252TRp4D6hGro2/7pkaTMKHPhsLvt74uHzxSpsemMw5wTh8mwDcdYyPnhiorpKGGwWmJErqWr3zcH8OBSoAvxB56Rhh,iv:6DrBxjHd6WHBy9Ks+yf1iCn9uuTO+8EKmnsxrsNtkFw=,tag:WoeTpOhNkiZlDAXoKeNRWg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdThUVlYvZVdGZXlVQlFi
            UGJSSU5KTlN0V0Fyd28xR1ZwclNodFFnTWhFCnhJVWM4TDFvQjVPdmlQSDhtdGVq
            d1MzaWM1LzZMcURlWUxsV2JCOTM0R00KLS0tIEZYa1ZLVGMwdTZYNVk0OFROL0do
            ekpNVEpHek1rLzFFSkhWNVhwcXI5TlEKOHs055JzZxd8A8UmQEhoW78VD3ipkqdd
            oRAurIyW9wT0RHEL7frNn58+w4hniNPkKpA+RdpKxeWOFmO9x6gJ4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T01:46:41Z"
    mac: ENC[AES256_GCM,data:AWUXfbOIdpwxIAoXlllOduCPZvSXG0gFqYHgqtaTkBijw0aC5nlgKyhTUhZ4dzpRifqh90A77XnGDurM7zlg1hyHn2yWRgzz4IiXYXRP7C6qut2KP0WKPzDrj4qzAyaXhqkyOS3HfnKt7rvPLi88rQbXhq6IS2syMoue483n/w8=,iv:JVmS/Jdvaml3TILcEqYA0lruW3RHR4ESTth47m7Qtkg=,tag:ctyoh2F6opTqNcG8d6pT9g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
