apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Nb9QihycvahqKt1MqqAkAsKyWvhU60bx84QzY4s0vYVwGN+m3Nyo0W9aJ08b55PK/HXQfKDgrNdbNpjzNPFX1BQMlhvRs5ZONd6+vLY6X92Y/6nCY711NXDWlIh2SopVrZhPHyl+XHf+IWN4krvoTSz5pX4gMa+RG9VXlMeFz/2wRf1E+N12zG8Qw0TXDefnuA7b42Xlg0X4mxsJr8j9DJO10oVJze18RgmTjer3ZX4cFuT7wMuvBm0aKoM7x7w3WHMQ3EoZE1QrbxxOF+FKJk4UIm8HvmafXvYJ7g9qDjIsWd7R/fAJFL1Vwq4lOOPGZ1P4CYMHQ2KtXXhYswDckaegtv5jbEavsBGaGhFy0IIjJvUPE1jH9TZWLdsYzb0M,iv:RsRZqhlWusOjKoe5dN248TEUXAe7hHV+Ra/WC4cdQhM=,tag:s2m3+XZYidZ/8LIENRP5lw==,type:str]
    identity.pub: ENC[AES256_GCM,data:wg2o+y0mqwEq+QDJHgXOYXO5GSwhbWOtDVpwFYCdDyotDVdfmz9Qxwt+iWG4VCSbxUATAyxHySaGDFEsZ+/48bZyC6tmt0x3wbjcVSMq9HFsynJzUyY+ukoNjw6AnLZP4MzhocjKqY+6DbYN8268Q8D9LNxIKUfWX6iVXFR59NqCX/vaV3PYUpKxwwh8fSeV6NZT6wzEDWwifsvXnI7SIrAXliFmFUGjzFvxPOjAz1g7ayZ3ILI06Nsw+BvCwqNhFL2fmlIi0Q9HWNz+kg==,iv:TspFRh8L7MFQWONtdlHgKEIh8XrQFyjOaTkrGu/8zeQ=,tag:ASt4tGQMCS+Zt6grRzsqmg==,type:str]
    known_hosts: ENC[AES256_GCM,data:yzDXXbSiOZLoFSIhMfhtFuv0lT6Tko5jr2sxCKFhx7DV2k6gdDMGjb3UfUy9q6YWrW6xfiWYqLS1Xd26BrTL6c9Llvz6WuBnrOfltPvjvXy6NAghmziEYAY3TYqLvRyC//HzbWvnJBlD4rkZkEa1KQg09teadZezESV7fuHhEoCaNOQKYlff4sMzSY6gJ7MEUMy7xYW2ckOuA9fDcoB/rqjk91kqLwaWr5cH,iv:8VlrcnDSS3Ru/fuIEGUoizav1Vv4twXjkqPLFNdsobA=,tag:H1cikrWmj7gIEeMKXrZs0w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YkZ3ZGxxejNRaUZYaCtk
            cGxmVjFMNi9mNkJIZmVUa0VMK3pJSmI4azI4CllucmNFa2hwWGJ5amx6cG9yYmV2
            UHVyRVlHNUw0SjB3R2JXUFJIWDNBMWMKLS0tIHcxQkd1cS9tcStFU21EUm55MEV2
            SGw5a0x4RWt4VGVnd2U0dnlkUzIzNkkKJtpGao6yuuDvO5YRizPnhgkxPXfMcjSj
            bgQlN4vThMlx+NI06kdlbw8VAF/25aWRZrJw+9mFWoRodIJ9LE2oXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T03:39:41Z"
    mac: ENC[AES256_GCM,data:fepmTPcAGbGWeN7uuGanrKV3NGX52ARXzc4MK2/IzIH7Y35EKGpC+P6Nokke7M+dCZo6nd/bbgWYozmnKJRv49BkwvYHaMHtR0j+8pY1QYfIGhbntNwgHtyuTWGDN+SzBj9kA0dGSd4wsSYas946SAX7iVziNxXkOoFIq1a7gO8=,iv:5BFoYbS6sxhiRtjxVpGOatz9PWKyQKyNf4S07BAr9GQ=,tag:CKUdmysZW0e512qs/d/8bw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
