apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:JAWeL9Ryv7mPln22O2tT1AFs7i12r8dT6r49e0sUzSt4Ng6rrdo4zxqwNTX84GCznH11ya5NHdOckhCavATSKu4psU3c33GL5lqmE7Z997CbUTn482cdAWDBLguUxFOYKIZ9Rxb5TtSEgNdSFAwce9cbR7PSB3loRVLgEa0bqBwivt1giirBMyWJcuMnuCXaczr1FERn6TlQ/dvvwuZXL1/oE8V3sO2tO3GcuGB716PuFPwnOGrLXOV8gx1JubVXNphInJ3JRLOhRDBndvZJOo1ZSTRAt9cvsfVBLvJDxxMWh8V3CABDhT9deI62HALRFO8KSIErqoNRwDNtjOhRPD2XL/DD94O/6/hz6cGVJ0OY9ubFpR8YyxUC6aKGSILY,iv:5809PDb+EkGdmcJTXbdLth22HIffon6otpuCHiTMdns=,tag:d6S8cikOohFQ5a0Y+8i4dw==,type:str]
    identity.pub: ENC[AES256_GCM,data:+R3jE3qNcYplnmtrsbcjRSfd04WARybJVfpWSeK5VtUp1X8i5gzN55tc1FUhrhnIqcsDDc8YVDVAgK9zePSLVIPSEHlRF6v84XIR839vBzhDJp6QAvOITwXigqsIlg+iVD/aSqPgQvfU/DVas6ORtu6jNJLW9WuAyFdS+NPIk7FI+X6PTaGQkUaBahHtO6ik6f2niTeet+CNG/8RZkjScLwJNuNh/Krilr0KVVBbd7enKOdcChN5c00SfQ+nq/Q0eZQJ4Q4+0nsfaM7Nyw==,iv:SpimyUErw6X6Z9SO8KTepURz2whd/SSGvgVyLLx2/DA=,tag:ZhfGmc+nKyYkR4jZj0N6gA==,type:str]
    known_hosts: ENC[AES256_GCM,data:q1uM3gAlujN9Loy4P38Q5S5cOm7c9Mg00nso7Jb3OaLRWTekP/dOLWbl6K5Vs30JSBD26mve9JstRVnZkpD//ffIrdUrBWp+D0uyhaPVf5Kt2AL6zWQcMPK+ZV+A4QGR24gn5XQFBGM5XgWjr/mnXAVpELmN+Z9W7p9f3bmTFBh1t3Qr79WhNH0BeQj/9MqKBxrMgJXY/3H2kmHuDKqYaYY4HVQXzIuEukAt,iv:AfBAGToPr+LENEfrnL5cZvLa3ABt8GxNrglrFr6m5CY=,tag:J3IQOV+d1axMjW8+/S2Q9w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvL1libStFUmt6TzRNUTAy
            WmE0RTNoakl1Ky9hanZCOVZDUyt4a2Jjd21nCmR0b05oQmlGWE9udzgzNEFFN0Q4
            MXFrRTZRSmc5S3NleFB6Y1JEZVFKeUkKLS0tIFlxZEE5OGtBYzVORnl1S0ZlR3BJ
            MGdUWWcra29LWVNqVkVPK3JBenE3K0kKU9wLs9IIQLodyUEGfvXljVgQ3d8M8rXr
            sPwkA41EY4swDa6vKa4sSDux33VLC0pRAkPllRvwBuZGiVMoOqQPVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T06:47:19Z"
    mac: ENC[AES256_GCM,data:j4gkQeG6ERHft5sbhipzix5vRagDm9XNuClT8ePwBN21FF3BXY5YIkOSxp5dEWWhuBeYrcwccB1LBdhn10dGon/dx+3PTafwqwDEHWmsAm/1biI1fXw6kqhF2fjMapaCP7Ect106v85BUVnFR3CqtCS5G5UCNd1Dav1x1rBLUJg=,iv:/hCDBxqSTCZdDgMd+9ts6OM4HoFjNBsArJwtjdkdCF0=,tag:72dEI6YbxMhFzePvBUHouw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
