apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:bCs7ZSkgz6T15C6kjV9NhsXt2j3vkwnXGl53klWNjLHzwVNH2cYJ/3ZH6iY3HPnWeZWLJxbqohTkyIzBSiTrGalFxSVKNxNss4vdPxqIlEh8bmmUv57glIIDDVCll400nZHin5wO13+HgtOt1anLgfM3svxopf4fLOp/r9u+tlloe2/XszfxB+epIMh9Dx28jdFP1RwYzG8MYeEHawlTCMmxe+8Oin1nKT4og2a7GNZTxozmVHAFtqRQf79SDwGdj17xPi2CsriLWy8nW1wneb0arTHr7h8oKf2iYc6fXft17mZfmKDRjRkpRgEgiohb3yqplaK4c4pKS2ssZA4gUk48/6urosgNQlHqLDXchHlugoTGSFECS6d7MvH/RUPa,iv:cNAjmpHMEO4G934Wb0oQ/0rk+38mRhGR3KijS85p3HA=,tag:mKyC7ceVucTRYCJR5Zwf0g==,type:str]
    identity.pub: ENC[AES256_GCM,data:ucoOn7pZrXwBsHYY03ywWOrf7G3Ii9SLYj/9LqeUD1tfNJ1zelIJc/2EelhPCv609BtSBEO56mxFYn5w7HvWdf7Yq3z9BBjw58GyDdxPB3rsJ9Zoqo6EYDmt2EFLcbav1ChVlPTxx5tZepzoSUerfQelaQ59EB4CV94vGUvEhYoK4ewtHfJH8P8eF7lXO+TM8U/f/QfdU79GSwOc+vpHi3Jrb0s2+HULNoIsCCp7hmxMneC20r6YXlsZOEVZNpG5lb04FQn/M8e4NtiUIg==,iv:evOyIZwqzx9Va0CGdhy5RD+027k7Bdof1hdX2mnUkiU=,tag:IaPiQOLWXhox4rPCGRq/iA==,type:str]
    known_hosts: ENC[AES256_GCM,data:i2UCys0UkfOrPXzR61OdQLnRtC36kqkNnGVzlZBsV5KltCR/M/uUYIGMcy8SnkkF7nvedHiJyTb1qkuA7cItS0I/5DvHVYVyJ710TqTPyXMCh+Ho7UEfDUy8aVQwdOzceg7eUcQN/4sIrn+461Vb8ezmhsRO5EirTkxO7BWM50CvzKb3gR9B7kvP79kNCAA7LYsPOY1rgTiYvgy2YW415oL/dhIr26wRaEbC,iv:R3joYEz+gH3EbZXOjMLiaMRfHBW2xjFV/i6lExWW2J0=,tag:0Q+QmF8xbfNmWtvEVWyOhw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwME1vditpdEc2QTFFTEhj
            THd6Zkl4WEkxL0Z0YkxtNENZbUFseGlkZjFzCmVqMlVMTlBWekxoU1BIc1p5SzNY
            cFBmQkp1VlYrOHVmdHVSUkF1dnFvbUEKLS0tIGRCUFNIKzFUZDJ4MDdlY0VMZmxM
            OUttcmpBUU8rc3Z1d01zZ0ZGWG9VMU0K67fleZk0iPTJECTDZmH6NhksI6tuNYZH
            L2CbdLPQcY8/MmwLFEcB1EZcq0FaDc4nJGXa2uGv7nz1Lg351LLSSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T20:26:03Z"
    mac: ENC[AES256_GCM,data:3W+1Jvd7qVomCyVFYhSyoM1IlLzCZVRbeh1OMNuPht9qGfFBGzxjfFV2y6aYnK+OhBxvSv7JeC0GbTJp0GEe6JflVoUwhmyBbrNORC3pcsD/iSYmbePwR4Y+5tOGAviQ1/f8SlitO8BUuDEKnAGHIcGVNl3zwaKEkUq8LOGxgTc=,iv:oy2h2VUJOrGrLaZPveChISyCyltr3WqYP4ZIgQZo2XM=,tag:MPKRAnwZKZeBtJvczclq9w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
