apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:J+TSxphrlYv2J/ET9Cg3cxNpshwVIsiUSNb+Ds2eAiQbsaG4CdFavnPH/3wITWnOk/roEuXX1/O2dYsffJLpyBKVxgLe20ga6AK82rHFDZk4mQCrMn+NXZCM0xdQtfhERYxIR8PzC8MEoIPVYym2yd/d0nBAH66uPOV/pBglc42TQu0jUbOY+t9xbenJMPyX4LU1oyPSQuGCljLMqPYeSX0uju0S4CQc1qW2SZfE1si+a+GjPgOuyRQTMXk0PP4TNYBgwH5kVNRHSLvOQlGUHv+eLpsQftRe6jokzRorh0O/GVxQ0F8oJllXUnP047IIuVwdUmFeX+ktTj2Tgc1waplemzLQ2EUvYwkb6/YMUunenCY92J1anfk7jfJD6VJb,iv:sfSAWbgw7uBhCq4y5CjpxPZXAdgqbsuAfkNA2A3p094=,tag:uBzeej3mfZUTbb8uQ4e3pg==,type:str]
    identity.pub: ENC[AES256_GCM,data:s1Kv0ExRJCkWbS63Rh8s3e15u2+F/y3d+Ti93b7HkyKC+mo2/02mWDuwJVHLkrG1aazuDv7T0NNPjBl/xdHK9w46SDYGm9/MHP21VzHxAGIQ0WN/YNNWyZV2dZ7rRqLSlBcmVV+iE6JCdu2ywyZdzPN6bFLkZwNCtEPQxeWyKf1bx4w8i6I7shF86eRM5tr7qZoDblvzm437bG6CQLvY49uiP2cH0fwLbarGHeXWMQAp9XPIEWE0lgWC/DlPOVopSIIg42sONquW7GwOeA==,iv:1KP889nzZjlM3sGkawIPFuPkWf1Ets22LXnCecZ8g00=,tag:8wsA3PyAqdjKGUeKedDglg==,type:str]
    known_hosts: ENC[AES256_GCM,data:dgD9iSm2/wpF/dOuZyskuY8uG6fLcs0WqoqpuRazhf5lqDzersUkB33xeuulsFjqOsk8C+6bQY9ZxtRarIAzfW1lWtHsMRtw99WayJW9Zujm/gmZ3uv/N3irF3COaWeavKBlVWFKzbcDOWOKTP0HsC5clk994djfn4wvpqZUsA51UucHHeaQDyS9/K/yY9anf6rlY8FAJZ4dbhMUw9DrOf64uotPs3SGkKhI,iv:YilLEmy0Nf0GEGgyThgCxLiJqYxZUi1l94zWUcAEdNg=,tag:QL3hV9xAEvl9gQMkon9o2Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NFZaUnJHSUV0SnpzaVBH
            cGhSY2h5bTBxaUR5djlrckwyU3dVYVFIaEM4CndrSlpnaEdZRjVxZGRYTGxvSVlN
            N2lJcjkraDZRUU1vK2EwN2I0b085VFUKLS0tIHRKNUVwd2lIUkR0NGJER2x5TjhJ
            U0JLaDJhamNDeXUvNGFwYVJtRzk1UjgKxrYdktpLcD85qtX5QdZ0LDaAVyFO/jyo
            D6CrvVpi+O8CsKHqEJhd+cAUFB+gllZTs2JVTqDUo3hBsizbBDT+zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T23:26:10Z"
    mac: ENC[AES256_GCM,data:IhjHjYzU92CQ/EYMvDhQlCk9LU5WwpvD17jj/wCiBcSuEdbkH4+64kb9EUTFD0DTPkehyrtOREqPEmyHc/PYg5TodLMY/qXZqiUJnDkEuYPW3AiVoCr1NiyGE90V0GcMRJpZY3+PdKEXybZc8T0k0nroX3cMfa3iag1Rhr3stvI=,iv:Q6EVmctlRmZ5CnOsK8d0IdY4BwesXCysMOYh8zbS4yo=,tag:Mzwl2pPK+TIQSYKfOLIwmA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
