apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:D46K8szfAP7J6GZ75q1pplxGFxa1y6SrPuOiNJt5Q2rTJr5oRdVYluQ9UzkiT1SPUgUiWkqppJnyyX8o4U6+5n6Xs6S+R5FDtRvLCB6+DC7p1RS14P6Yn0jWfcMR+GQ3emvoQ1h/FbDowb/+WPuItLLkdKEWBCNL2QTH48E+t0EvGdCFSj1klD5DlTe9+J/UomeyBqwk5I0JZ4hDu9dSkwgAjHoXtVlANxJwDytlPeT/Uo8eHi9mzaoF+8B3AGCC7qxgM3mNE+05J/UUtxYm4AYLkLJJA21UH3jDnn+szQM0pYA1pwMBry7QUP6ridcBmEOU95Oc0gxBXYD5PA+EJlFRkimGoc2QAGj1YrmByLAZ+Y9WDys3v7E/+BjWvRdo,iv:v8gHkr8gVfqcXARsFHZnFL9BKHMlCAqU0D7av8hyEew=,tag:hKUkX0nKHcViDE11L6sl0A==,type:str]
    identity.pub: ENC[AES256_GCM,data:KTcoivYR+c3mF2l9s/0ZhciWoVbpwwhhiJMHffbC4kA1L+9bG4xBznOtgFwcpM/a3j6piVDUip5NyyvrZA8mPj3+0aVnwU/L7OEA6FNt2RcZofB2U5QgfcNZwCUSr9cjo3tGm2cZmnVtLobDEJ/Waal6hQC1A94Sqj9OL28xUO69shCF8ysmHhlK6/31Deo9DddflnnbEBJKe8PSf6UvNX8Ywrz2rZElOiHzdukC/WiKi9VjbRDx005BbHanThcJ7P3Di8BIlA1e2/5fTQ==,iv:oGuoF9WLQJtALPLzBtEM05Ew/b2P3dEJ/ZPmW3oNeLY=,tag:UPiILLC+2TOMnIg7KHGbbg==,type:str]
    known_hosts: ENC[AES256_GCM,data:pi3wFljtuZdwfR9MeDZXoZhkJhun8WsKWEkKzlA1JbxWX27ADYehb2lDipq5+UPX+R+U4TzgFKVbk6k9ORlKatmBLksXHn1edYbM7NmbqdOOBMqhuffwzGvYe1XtoyAIrPUzIMBnojptTf/ACKXi8gs1xV/XwhiYNFlA773HnmH9Sq2ioeJ8Q2VN4j7M7SaJeZFr4+r+vCdNCmlKGdxMWWRuDWy6DXYs70eW,iv:K7l3I5PV5aAaQ5kCX7v/76Ie9HfQW/1qe30mf0Tzj/8=,tag:zyCPAmKidCA50ymrFpunTw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5c1JSZlRJc3hsU1lUQnF2
            cy9zMU9QQllkUldLMStScTRxMGdqMUFkcFVBCnlZODQzRUU4RkcrYXZYNGFYMHJ5
            VWtMd000UGdWeGpCamZWQ3VTQWtRcmMKLS0tIEdLQVVGTkc3RjUrQXlNMVVnb3Z0
            TjRBenViMXBXbWxWY2gzQm1wNk4wQ1UKpdGUltQ4IAnnfV84WC6KsNfDSonkk5eT
            pUQ4tsunZoPrPfJvuMfMhk7knBGV40AiCkdvKqoUWxx2LhcjRao0nQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T02:18:29Z"
    mac: ENC[AES256_GCM,data:NQdR18WNUnEtByYiakhEw2xUtvKaEvdtcixhUeUSVYHzzULzwRFGDsyHJLTp+S2SJse+hy8QpTjfsaPdJhNz16K9ftFM5hCZRZ0uiBl4p2NAJMhGRyhfgz6UL/2rzIkkZjJeS3x/p3YYZsxEcupvGmJ7x88pVR6P132GG1Qsbrg=,iv:9BQelgGCWABJ0dUT9X/zpAxo878fXjLDHUD344JPGjk=,tag:+ECNdTylX1PjuKudog7XSw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
