apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:cVDzZYn5YDYwWbKfMh3B7ChsMFJoSPj+UmMl5yV4ri2LxyAk5WtSbI5iFYX/2izMvuA/4auB7gItED9oKVBZqU3fjI3NPj1uQhYH4mPRnRtmDKmWwzjMOm9ySSFj9htwHd+itxN2A8Xx+tnqaPyEEtJN2ieKZKqEsJLa4Vgd/dJPyd7HFCcRApsf6K+DDhR0Wruwqtmo63nFfz3cq69lXrgV4zQoHmicHr9OXDElr8P1V0/ILtj4EH6x+6gvAfG456vVshVJB20bBLjTY3elOXiQnrzm2IE5rp4ABQ8jl6b5H9gkhv9fK8A1RcMbuFuQ470kgUmSDCSWSNs2ecpJCYlNxM5boI7Jx3eusYNF6rsD+KeF43GcFYx2G09sxjA5,iv:CRIlmEspVxAJ243eANmkJyCxqLy9RbN37djAr/5ntPo=,tag:mow13XCMBx2Y5oalhKWRnA==,type:str]
    identity.pub: ENC[AES256_GCM,data:uLPOZxJkthmPaPUMxz4piAjraT8+tUyzXi6lIRKCfWXsYVA+q8z7n8cOQMqBP4fn3McDuAv4PjrQhFP9RnCLkSjshrgIstXDdztShKyXz85VZ66NFwR2Z71JFr3XHAyJIfebUhoFNgv5fvocG3hxW7vOMcsDOcTclzJTlDvIhngNITpkYitLpzlKP9zPp6YnP3nFg1li1cqoj/bWKfUxakHERy17fan2/90ZrLdArKM3bIeaPDLZJGr1iJfQ76/r3lz2WIu5+mcEuKb+DA==,iv:D2Jd/FHQPeZ+s6Ev9s/kgQBKGuPMzPrAwqbWeb9actg=,tag:caIVFxulYV8fFDJ85K3RnA==,type:str]
    known_hosts: ENC[AES256_GCM,data:+E6vjXm9gkFRbBFd/61HTw6uwF38cBPi+ZFlqfSTrDYjZnWdZKC/W+/UnR1/OE9Xc2VJJ3H+Xr6y0UO/frybR0rQjBe0MrndxQ3cTNxDJZuQJsNpuURRgPwMn5Z2XPrIWm8kfprP5rcuXDfsVCrnXT2A7n5fFEf68TjQBEMiuJNnjrZePNyKjgBae0/NDth5BYm1gIwuylw25AnNDRxDUNJGJRyElxz/r7+h,iv:t0Lhl7I2Mm4nqgI6b1Ef3OEKZ9p1bezkqNzb9+PGHFo=,tag:ZndC5Rkn52SxbuRaL2gKnA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQkdWTlpud3JNN2t6ZGpu
            a25Gc3MvVVkxbFFkVmh4SGJBT294c1hNb2tFCnBaaUJYMGZBVmI2dENWRFFhcC9V
            Rk5hS0QxMG5UUFRLSUtDS2cwOEhGdEEKLS0tIGN2aEF2ZXJEVVluSVhhUmZnRCtn
            MCtuY1JnYUxGT09lYTlaMmRSNW9TVUEKwMuR+wFkCwoWhUV9v6WmIgU0aKrgSzGx
            DW3KllzZiW8rRxamhV0ndrHy1z2ndwkevDst8aIe4DC91l4Xn6sD1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T00:06:09Z"
    mac: ENC[AES256_GCM,data:P8hoIVMjlMk1gJyGZUk+BG4O920w3Z458/N7lOKuYsMSsKQJQtawFi6i1B23CbnjjQDwc2GjTMxxK+KKOdiSCY8tnAnAQvLiaZFxKlRVBkjtNQ96S1rtWxpmizIq8vxpe2aaDx/f7l9fvb+0RdavsUU+NihXBgQBU9DZnKBrKQk=,iv:/vVyo8R6nkwR65LTIIxYQdpPl7bpHZfrOlMzXQaVTL8=,tag:P+waeYxTr/ODqsf6FHVdgA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
