apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:FozJPouvIU54VRmVD22A1fzWlR0GoMLdG7DyS3/ZpYT3efOC81dEiTJlstMwr14qtweKiAksNCRqSCiNs0Cb2Vv3rEUQSjzveBAS95UoCbRjKOostPUX/s51dc2HmEmG8N5ce99mC9fVPBMIOte9sRHYXgTlwZGbNcPQLfPRGor3ygP5J+NmSIn8qXdD5TOP/yn2uVZYI37jJaF7P4MejCi4tpKeBhH888fyIG08dQ4j1hdWNTxSR0xj8PlP1/3UVIKwAHS8RSPBTyBK1jE6bxEZhq+OfuZqS3CKuWrex1Tu2UxcqeFRmWDu48nhsc4GjuZjGv9JoxQgn8mW/W9Q6uBjaKZoxASMb4BjLARGsfEFudrGkv7BcVOMTNqtVVvG,iv:J8aa8NHw8gy9PquJ8jfFeCUjie/2MYlebJIQzHg7miY=,tag:xaYJxaCWa4LVYx3wDa/psw==,type:str]
    identity.pub: ENC[AES256_GCM,data:w3wIcDA4ObRHrc6DD72pRGmQmOYXpm2+o60UGd92gNzLJdKzpkeHJN8rRmn/U0ft42FLtFm1rk+V/ijsi28dmt+AK9ZZctPGIQjd5NEI36G+NdPN1qnbyJq07OH27ogJZweLJQHonnwf7u7/vJJFLCd9Ctn2UgzGXlf/TL7UGjZPNFKJCHNI10haV85N4YtBlTCuDBArC/Tp9mKRiw1uWxqWuGdZsBmHQErbfvyUeRSKJPiC1pohkLN8ZAxLpL+NvNMmYPedf//2nkdPWw==,iv:2nA8503fTlrAhDghFRNc5ntmszFaMVHKzKoODDDiFbY=,tag:Z5h5BW3luD9z2snzbW9y1A==,type:str]
    known_hosts: ENC[AES256_GCM,data:KODIdzE6FSODtIK+QZWxoW7P9+Nl3uJDakgdCZKcXmObw/6WD4rlpzClTrfbbff/wEHazp6JRJmbO+QCJeqiEysY3YoL6IypCf7GvT2EZssDTFFzBVb7xheJuKUTJjdIa2PKQXwPlOUuztSFoYIpPHGW+AusL1lTEy50vVAWBd+rS9g8pjgziUILkc27rMA9GpKZhLXe4RQVwggVBtdRPv/v/Sp5Lt4CjMWI,iv:4wv+FF5MSRbZGMYJ+uou/rOUzrInc/gcxFVfrK60gBw=,tag:p9QLeInBk7qF3yRWUnqBEg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWEdIcjlab2plNHVFYk83
            eVI1c0FhVjdnN0pBd1kza3dRc3dHWEVCd1U4CnJFOFAxREJWaVYrcW03MS8xU2h1
            dmEyODlid0ZGK1FPdUdKMVBZTmNrQncKLS0tIDFidVhyeGNsem1LaFJOdStJYzAy
            WGNucTRaMlhvSmlQaUlWVGg0OXRIN00KIiQRtFbLxCt45pYRPZgFa7sMZ/Lk6S+F
            AjvyGzNfx4DxemmIoSAo+OZXr2qQ6vh4ndx2cLT7dqnPAPR4Sgf+1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T21:53:12Z"
    mac: ENC[AES256_GCM,data:3KzfV0agXo8IaxMXObuBGdPnk34kAXoJ3qzaUi9zS+KN30rjSX5wxk4AFFDpKIXQGXjVUt8e9Csg8Yo0gE8po24VKNLhk7ttjfB/Ow/vFFqLxJQ0hYhuPH9V7rvqMbPGSd6tN+iuags5qITSwJPiuXyCPlgDbCM3+2jLOD6AB0Y=,iv:vqFfmaccmX2Tk6jf00T/dTaI8xbBCajMi9fQGfL2vPE=,tag:bT8UY+hmy/Ph3IbFN7KlcA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
