apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:FAvEid2hvkSu4JUertjR00OWVzU2kUruVtEAIqe/wGs34sFdz9WNC4/kGUQrMOZpUoYBolD188XdT/wTp1bry0BPSGdXYEOu0gD+n9pJqEea2AZ5CgfAqUprFcUZZPLkrVpLiANfWMRe0+aSe/bbW3WPv2o6q7Y1X7jSt1lMJofexaNXuUEF4S0Ba9LEQEVOlaxkB7Sv/iRZMRVecufNqrhqZpdJq0WQSH3YucFgly3FwH+6i34cyQyRvoBIlhazLMyabJ73ihEyLg9ErpTA+l/49a7K33kRBBODVpHIwa49GdzQXEyVnoHgRCtdC7QRVo5VG1wjG6qx3kuE7q2fsFAs+oS6Nd/pbV7uFVZRX8mK9URG3+8BmNnDDX4zBU3R,iv:TmKOPxFBhZsL2RIuZPti5WetMCbDlW42KqgI1iLrGu4=,tag:9yBRtvVEHZGII9L0deZqdQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Z7zDuUEJ+duEzKtj8wL2iU+12ApJuA5N6D0cGJijojV0Ns6NsjbJmb3/KesRcbBN9PrSW+R7Px/kjbdMOKzdKia4Y71EUiWYn2+xTDJY686++7v7WtWA81s9VmtazPYWxheW4OGpPcPQlqcxstqPquoZsdbdqYswQIQb6Awy6J49Yd7rkEA4eSLc/SvM9+4Jgr7+eoqXDZ7AzpzC3e/jB69wvI+O+nwE7/UShNJ9DtkNo/JwDvHtzT53V3BXRrMXAusTAUjeNKUa776yGA==,iv:Kp4YpQf5BJp5Gm+U4yBN4wLclFxTFEi2SMsxjkGaklI=,tag:UQ3t8hZ50IZtmiwNOAOBVA==,type:str]
    known_hosts: ENC[AES256_GCM,data:yxVgXxA7b7+tYh5iJCoVLTbPlUuHOI+wUPI41ue3YcQP/mPSyDKutmtjCjd4WzXxtu2kUjNBI7PNdEfXtUFKl8efoxiyzLpZjKTn0L9itTA5Iha6heDLIp5mOomMEkjmOL+UsT0Wkkxnx7+S2rAD6xbhSExBaEss6/O09GbRLNO7zyog9dIUnkozNBVadl5UPQ8N/QqpBlirUjpqfHx4aKctviDp3w3nYlKp,iv:j0TIpXi5NDYdlq5W+rtVulbO253zjrFZg9w+liX7KHM=,tag:y8SnBOn4j/QdThLowvowXA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1T0ZmSFV0SHpvdVAwWUNv
            RHoyazlaUW4wd2RnNkJiRkJhQW9yMlpEaXo4Ckxjb0p0WGF2RVFpbHJHbDY2MEZn
            U3F1U2p2QzhRaTNqSEhlVitRdTVpWTgKLS0tIGtDcExibkIvRmhiN3lSNTU5T01h
            Nkp6UW0wSGpnUzNBUTRNOHFPWlltVDgK4ssAbV/nmQUQpU7st+HqBOkRSNf9qmGo
            X/3rWjeGMUOCR2T1VKKLNN7ACqeMTFJFKKfDc0t2rn0WQcWo3BBK5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T15:49:57Z"
    mac: ENC[AES256_GCM,data:2340URGhq1bVwKLf93XgBqt5FynIt4xqsJfl+vvIYdCHJxf4xDpJ/m8KXzrTRk/pP0+uLpQhz/A/aVphoCW6bQZ0rn5OKdwDYfDQuyr8RTC+xpyJ15ohyJQGRowi0DGx64ckEAtJE8P88/DLcWVfNPKe0oWCRtDIX9ktfyoZI6k=,iv:KUYuh2LCMVm1zV/zzY7QD0mWp/G+V6lJYs+x34gevaM=,tag:1uYyU9ueUuIDerdspl5DZA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
