apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jHfyzcztxwjLeeE7FinJvE8jLdXczrdVqHjrkUYfpD8O8D2jf4wG7L5vFabnElPgoEZfrcUC7XKCt3RyU/dGtMWYKNyxfhd9dtvgKshZUiguLGUMbl/QYXaSXSWmV2HwI06A03dbhuNv5h0oYciLbK2qYmrhqVrmGC5ZbFiBAmjJAW87AuvKCsV1pQJdN9c1MSgYBJPPhdri8bChnwR7ChDLb8f/VJ1OjpBhqAAxaiUSl32kdut+kO0CsWUGqwoW/qh1Ey3HN/R7eFgpErVPCloCMhhd8jLC6/Mje0+AIX1lctwV9btC77kjklrG6/NHTwZEQpLRVAHQj1cu4ilDF6MXwmEsVyjN8olvnQSIc/TAr9VOuZWoacNyYxXe1Q2g,iv:lz86uwig4P1tTZhMyyi/W2VyfssBm46YpBRtu8hGm0M=,tag:NbN44EnqYVftyF+H/pG/LA==,type:str]
    identity.pub: ENC[AES256_GCM,data:GM0XAbJo5Bl5COCzXyOUe5F/gQDlmJkLREeirPP7NbDLf1O8IgV9Ght/5NhB4yz9KuDHdr5d7kpa2fg41ZSuITJSKfl8Wu83nG8mlBTnVQP6onhSqC1Nd8cpNMUGT5uOVM7cDo64LwwSnVN/fV1MwOdCSLOIIZZhj6kFCXpKSkdIjhwNxeWCtcV8tWaNO+1sqq6mz0U83+lNNXplbaVhP2UMtcp/ok3CsjsgNUaWSH8ndga8lFAPsH1GzCz12DpQ4kRpUe1GV0P4ZL52xw==,iv:fnz2ZfdaqgVJFLy2uYhDw5mUpRXRamvyHHWxBvTUdIU=,tag:QrwaMXHtOBtWJt4FKadc9w==,type:str]
    known_hosts: ENC[AES256_GCM,data:35o+shO5mX6j+Ny14efAzfK6HIX0vh0VgAVphXoZWDHYEOLrXRnmqmBrUsj/QaAGZU9TjWBpFNdIU09318xbi0GONloAyvl/N/wQ/24XGD3G1ujUfH/hNBsF7ftbeV2R5TryQtisYdcK8DMEMqCZtrGvc7iaxVdCiOrra8wf+2WTiIxBBtAspb7PcwXK2E0XKi+99aBFMvxQ5bGwSRdpFkTnZDUe5ahAd2w3,iv:SO78XiaUpe3+MxEG/D3f+bT67OkBWK7e9eXE1f5PkVw=,tag:yk9E77RO8TePj9HTPF66Bg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTThwaDVzRExKRHF2Qk9H
            ZlFsMFpnanZUakNIS3cyNFljUlNJY0E3aVhjCjVmQyt4clZvMklaZ0ZWQ0Q3WWdJ
            SDN6ZU8xeW96NVVhK3d2cEZaWG1RQUkKLS0tIHRHTTRCckducXpRdkd3cUlVVFpT
            ZTQ4cTJtZndwNE0yWWluK0JVZER5UTgK5XlQW9APJF5oIJmtuG3md7w7mJ9uoJsP
            UU5C2YOjdCPwqJz19XwYj7BVc4l6f9s9cLYnLSV6YonSVzg3YN1YuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T20:28:59Z"
    mac: ENC[AES256_GCM,data:25E7viBzQKdUEuJhvy0YjF/S39bWysNcG9bC3uJnR002WL021tGdtF5tNlVaXpqQldGLpCuXaZKySd2HVi0uGThNm93qNk5yU2gGaprQydA/TLc8Kg0+pgH0zPzr4BJVbIoBUM1N2HFuZUMRWRqJNGGLGyAm935T2N1HKub0EwA=,iv:aksAigWBt4nrkbqkevSmTzVS/s2lSdes0s/asHyCvuw=,tag:Ln3J6KDPXBF7MbgmRD2SGA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
