apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wYjex3EtPyDBhM7ps/GD8y3wNIRdP9oMulhywyQK8f7XWA4o6pcfl2LwBfQVl0k2vOExyrsHzWc6xVuIRP6hsQeC2Ih3fiIV1dv4iX75nzwSRPFGnxEgBHgvxexy02efsenpLZJ1d0tEJ490XlHgxKizY9zFn0+Yp2CDRmmZCrL99v2ucOBP1YNg+CM6vnoFmvnhX/0n93imWx1zPSVttqAlQe0gge18D/fNEel5RIXzbbLBFHK3ODMAN1wZTbYqQEIL2JaxYK9y1aQYhYB+HGDpzLT75GZ3ACmVeH7U3ccgfhhUuva/wMVPpYAtzu80uvbCLjGCO984UYfu+ZTA3AB1EWrvQv53MbirBhbVrtfhCpWEInjQ6TsD54kvqAjl,iv:uxmdW201Mhozs66Urtx0O/Lgxzf22B8wI4allidDsfw=,tag:WRtsdOvkN+F4iRxtTaaIpg==,type:str]
    identity.pub: ENC[AES256_GCM,data:EALidr1Ok0EhFXSf48PqyNO6+bc2H+imoDlkKlJTFQ9xZSYBFUMld3BoRBTXXYEeeVbiFjNCZVlYEDgUz7nndd9a7vE/BG6JMIc9UpKCiZWhXYSSm4XtIBov0yHbiir8GBdxtt+niA0qqqGW0f+pIvucl+qJn/ja6w08up/5yx6WIIkMt56iiWkIyZAjz59lWsT9Zr/0/vhB8iftHiF7gE7PE5pAH6XNVWl5XbRc87Xm2kusaa8IXYL4LaqsNPL0rkKOfQ8iDGZ6tyMpAg==,iv:Io3m9s4kWfPVA11Lis+p4Jvq8MLxZ7z9ln9XyA2Bfdo=,tag:BNI+Qan7nl+YMnNj/x0kqQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:1WSQBuDJfYEpyOvQGn29k5lxnXz/6gfhGy60hY40O1oEX6PzPWCE5u4uICHodZSU2tyhUPaHAdgSFxgnzFNSvfMRrciMUlfOzUnosjOxPVEhqNsil8cmiyR9wLo5C+Ss8WILOAsKDQum2aXpwfVMWxBnD0uQ1iXiyT5+K9XCJOS0QRfLvxEuNPpuzLRZpuChoD9mCKPtv2+WCVDlaNwkxZWHel0owU8Ns96d,iv:UPs+GVgkILvF9pBm4wJ6+0tC9/LPhGnAM0+e0xqkWtQ=,tag:nfh/eobRviiEpTUHG0wodA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bnNhd3VMLzRaUTJxWm1Z
            UFNWbDA1L1E4VEt5SUo1Mk9TSVlIOG9Fd3o4CkpFMHVSQ1dJSm5aTzBDYmc2cjFY
            NHZkekxFVU5hekR0SDVSMDRNRXhvUTAKLS0tIGFNMWpKK0xLWmM4c3JESnUxb29D
            bzRRdVpKUWR6QThPTTI5OHhEcUIraXMKAFghrOIriAT2BQycL58c1vhNk0v5mzjl
            F1FeOabz1ATdvcVxob5JfbconYSfvyfyDpr9XsDPiILN3p8okl1HQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T07:30:15Z"
    mac: ENC[AES256_GCM,data:EU9HQy1R+nW/XNjJTPM5UDN+9rNvWG5qOjCw0qTbdOv/zbndV3LmrtuAXD3y/HZveZBDNIGg2x/YodRJ9wHE07djygvtNxG6OWgbikVvza51YlWTUERQuSLPEh8pAKsp3tdxxENGKHr5KSEQ6xn9k5Rd2FOHOAd81iSowNGFIjA=,iv:E15mfIFHBKTQJ3KTfL/oxlQ2TQc3g4ZyZiu7osjESOA=,tag:NcgD3rItJpyAu/LM1nxn6Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
