apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:7977EFUKi7i71bYuEVk+qHHYSBANviawpVN2hdAVMu0ruY8TzAGkgmxOQvlE5wKJC09uq0Z/EEAzz8vfe9NZl7Hn2Zo19em/hA78bN2KLpJ0//cdIBKYa3UprFKtQrSkInAIMYw4a19C7lGUdg9pwmyaChf3XT+webo7hyKXEtJjWNz1UC0k+NCCMx+RySLrKSPNJUMYqUFNWgndNUCA+j0gopoxaNqEPsiE0O4JrWnUlMLyiFTbIxvQxlWmgRa1vAmQhtYbCgWu8NMTn3kOL9UuZ1crV0pmy8w4bcKHmBYAd4eh+b692GFYAqBPwzxOYAXQXBG9KRr4FNH9rzBJBipksypFvq+G+bK0HAnBUF35PC0Ps120I3LIPher+kZd,iv:mxteR445W4zPbpBZfrHednENeGXRH3u77as08aLRftc=,tag:fqCTaZoMSw/aao4+9KNvAA==,type:str]
    identity.pub: ENC[AES256_GCM,data:VZO7bPGdk4N6Fv8GQwXy8LXzPmJ8oAqTDeLbhFdnEiPoVvdD/1lGXL6UzcJeR0KEnlkqUlqF4ILTe8NI57pNpI3lxORq9N0D+lkMsehi0R1ZYxOaI8IngYiGZaTFA6WUfKZaIjTvM3ZAgsyyns/5wT8kLBlni1OQssNK9MG5r2KkgOZEvzlQzyx0ptSBbNFz8YlBf2nfSDgktkxEO0xzwL5S5RoA5dIVFZB5VvhBgDpMOUPv87oJZc/21El3bFt2ljqvnF32SY1KemRlwA==,iv:fKfDGYGG521ghszPp1wQi0m6RVbEc3DmTfMXpYULL7w=,tag:35JLz4/EmBbwEFxUaqlp8Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:tDP+toZK11OK6Woeekwkh4+rqQoXu2e5vjO7H+8m0eiC4VCykdv78awocaQH9XSMUAwazya5PJZKlCeVS7Nl2SyyupVTg6jG9efq/ya/9ARHpOGyTNKdgrNctZheK7xCbKHeZXeoTR9soBpLxDNT2hH5mHYge/rJC0VGSzAOLJj4jOT3KquQovxZ6yRyUM14uUEdlmc2nl5/1jnTPqcfqIqpTJJ3TOS+D7hi,iv:/UFNLS1h0Eubjjhn3xQm7LUnRA0p9KPeMLbRiWtXSq4=,tag:lmGLMnTOXjh07+Iqo32asA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNFF5OGFqWXc1OUNhU2k3
            eGRYY244cTBScEJjRkdlQ2dESk02UkJNaFRZClIwblZuTTNQSW5uN3NiNDBWQkdQ
            K1RJbE5HQVNsZnRRVzhmbU8xWHBUTUkKLS0tIGxEYXFYZUFYLzlSTVdUa2hhbmdz
            enpjamdLNjQ4ZnpkUnhFY0wvRnBBTGcKzss/wFTV0kRCZQsnGB/yirX/N2WzvRmx
            +1+TCcuH/wb9OWq5FdQW2T1/SlpHlV7WeSs9OAauU102C177lxkJlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T21:34:49Z"
    mac: ENC[AES256_GCM,data:TEtpTy/p+S38MfyewTkzZOcLsvN7/Lx9yc2h5Vr7g5NQgm6IVFFJDLggAned5mWLDOfht4eRmntJPodSwcV1O6udgYF8CqrqA9CfyPlKpSLVBzWoXVFbaoQNFcx75ZM5xTf7JSKSA+iSpdVkNQwoLU4t3lQlLziszeOLAlgViF0=,iv:AgjGmvMy5HmcFmeam1bRnjqEmag7nrhO6I7QyxxM8/g=,tag:DlaBrVaA+sxB8MKTIUaWqA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
