apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:VhtGgMIdNSmeKtiE/mA3sg3w3IL4sMSpKkIxOwp7i36qPY+EerlhGNjA8ZSIWEBN6OSS6HVdNuxIvnjLthufqRrZDfvsgk265KOhRAu0ycJh6CRN2Is0sUzqUdKh+gUD1HCTvNUmEN6YzKnTUdHxn539s61xk41VZK5wl7kfuCz9/f5w+A6GmNO7Q6Y6VCnJZXrxkRMXL7ZtTQCOdzE3+6TfG6P6mBq7Mbbc/T4at2MrzlLvU1DauAqSkhTVBhw6jW9Bg5JYp6HyM9xAp8MBJR6h+Oy78geiRkiT5BbKgRkmIMO2ZSP9Sos2W87Z32ktTLbuLoot1xIr/JQsm+/KCsP9tX/rh+Wn6+XjMYORjg7V0fifni8Hj+Enif+THlHX,iv:lL32NQCMasNBud0sZlZP0rO+G5mC8exwHDrVTv83ZFI=,tag:cF1/DgDTvWN9hmy56Imxsw==,type:str]
    identity.pub: ENC[AES256_GCM,data:s8GpEl4n80b+TG5sH0Barsb+mvN8eH+eICDVpWW+jSSBljKOKqK3eh5W4VC1iF0vFWWxj5+lIs7RqpO31IVNXNBCrwmZs4Gaf0d/G+rCk+QPU/EPT62wzOFFNmiGCGBn6UV/jco0NNqpc31KyWaPTGKraorNsj30yLyts4ZFxjW0vNbbMTomP8+0Y+6tf5j7C8FMxvTSzA7VW6XM9pYzeKY9lcWukvVWG+WQz7uBBIvLlgui7HYXX0jx4baXDnwTiDG6ewCM7Ue9F5M/wQ==,iv:/BbLnEZ9PIJVbZ1tJTGsyUrNAS+rZwYP3wTOvckkOhU=,tag:U9u7jHZ6KDWTRCoShyOv0Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:yOA8IKEAjUtwM9n1DQgBET/SY1P9++jj7PINTmJcRjEczlcqSuzmPqk1AgB2DDDi3ioDsMcT5wdGlpqoNIjuor1xfqphSFDH+ILxHSEnc8dlCdiZiqxHZD87wxA3nNxTWlrdeUPwm3QtJ60AJXjvEdZ/u0uMqWsFskF+5OYdr0KoFN9U+JcXi5/m6v/F46BRZJikVM/u7oEObcT77nFFdFcNDnuWsg7l3kgI,iv:CRnI/Htupwq6A9vXQFKmNo37Gab1M95iiMLGeLKcPao=,tag:yWe/PYRv0o7UlW+rG7RDkA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTFVaNStsNnd2YTRaM2FS
            Q201ZkE3cHhYanA0V0lzNkRHVU8xd2U5RUFrCkxBRWlsWXIrQ0hYRXNBWUd3ajdJ
            MVBoUjFCRks0OHorUmhpamVHYUZ3dlEKLS0tIGpYYUllS241WE03c3czdmc5K1l1
            dnlvb2QvaDRIdVV3c0JMUlUxZE1uYjgKNlJ42uBGCcG3no87ALbWe4cNrD7+3C77
            txWr5j+h9MPstI5V1oJbMVPPHUVrC791ETc5iGuqmUdCA5VwA0UJnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T19:23:48Z"
    mac: ENC[AES256_GCM,data:LLhqs0azBOzHXx+zRQVFhxrog4q4Dhc4MrEZkASg4MhmPKZei8+LDOR6RTuezgAbo6hjQF20APW7DSqYbTMfH4DvqiObTQNmT045hJ6efqAfU7W1iV8gPCw0z4kIEOzS4S5bOAnsQ9/opNO618rqAGW0BP4VarwCY/CV2ECvROY=,iv:Yj5B5iJ9+HT2Z4vCmENynBYblSZHpYmnvoHeD2ObfNk=,tag:w56/EIkFkzS/sma3SbJchQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
