apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:EPExvpAl9h/HO93iny+7ymFYZng4i/RcXZ4VvZ/c7FegFDTUdW+mNLU2OT9wm/03WKQS07XZZGKVevJDHZB4Fn13uRx45NJ/VfO9pR8gV7n6Ym8hLoVmHXaIaMBbhWHhbmydvmLO3KRGFuYQkbBBssAxZl2Gg/BKK360ppuhdtwiqIr8lbn5dZ7uau+rn0l0CKIXz3VyEPN2Jt2s2g6ahXN7vBwSqG7IEeZcDsDrtUZ4iXi/qxzUNctxHaHgtR8MnCZbwxvgjLtaw2CqhjUhaDPd8EyIq20P92HKdVMArs/OE/9RFfV1LTqOMv1mvkbm2BC5Z2XW3Ih8uNECu3PppYyxT0MnmeOJgq67LBy7PIAXnp9i7ufNqtk9MISCBjIv,iv:ZfMZR1UYcGvDnDUyPUb0Tq6DBeDEAFu2kj+MSr7+Dno=,tag:GKaJ9MezQvr2ShfDVF3QHg==,type:str]
    identity.pub: ENC[AES256_GCM,data:d9dtvhLFxs3y8slrTJkcf+6pMvR9htNncEsm69Rgf4kcRbeFCNiLP/fmBs/64QXY6gk02ixdK9gF26HuOe256Ql05FqA3Kgskber52u5Irxr0WGWuumUTw0F0EdKuWIq7icAdfTgfnkJqPVnEqPiaUt58+9kRncDcgqtMWuGDwB9gnoi/lzWtDkvFM02Y6uTnyIqFCJFT3uuy70gQea7tFjU2ih2t06v15vevzttQ3TsfP9H/NUzNj8rh4vacwks7xORyjxha55CT/EYTQ==,iv:9bD61rbyYlTM6KzRcJ7F+0pntGA3aEyn0601cXBmJAw=,tag:eBCmCZzXS6YAk+HQLBpjeA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Clq6Om/qoqfzdr4Qe1v/26YSmfmv2h1rsCyzd+3qCXF5DCo9jjpDHdmKOglisjPRMYxrDqJ/fpTkZSUfWXEpBeXEhYqeYvInfu51ZABeUKTdeVi992lr0gwEKxWF8pz7Lo26yRwlToP23r3O1qW0UZ+7Qs51fyEVhvNoxFmfhVwx1bZh/eU0mKGVtMqEDh6/F1cUAtPPUVXbFm4eCAewbG/eNLKHXLSoyxRZ,iv:f+Rz/47fzWh00nRkTmCYmdRv8u0BYzOQRxPttobsjr0=,tag:v5/l8JftuNRIU7gDK15x9A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bVhvTFFONklabFdYdnNU
            Q2xFQ3AyaEtkUEowS0JsL1VLUUdiZGlzMm1RCkZQZ0hsb0FQMXV2dEcyeEI0NXZV
            cGEzMFk3bDFiMlpndnZjUVFaa3cybE0KLS0tIE8xT0FqZUluaUZlYkRhZk5lQ0p4
            S2xiL29lSkRPTy9pVjR6aG5RaHhSajAKDdDFfFa1eBoAuAJy0/xNIqNv5LHZcl0R
            +IVwa0VfYGXaU+9DnE7qOcgUFYZmeO2g3IHFI/2ZG9h/KmSQeR8x3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T20:19:40Z"
    mac: ENC[AES256_GCM,data:uQ7rMKkilFX8eFaObUpcGor0WnWG6UVvv9TgunnmmhERPeX7IkyL5MHg+Fv7X1PCQoc8+stkUUUyFSTUf8PDnNDzyB9l33se0zWVqTpkst2n9SFKD7lMnljVTqAWgtAdo10YV6SZcBvx5hvLPUM2KQYAymgse52il9Pb1PbSBuY=,iv:wv0LLyhkY1yZAc3JRzBeSs7n3L4mOykSwn00zFKFb6Y=,tag:EaTdqDscns1LnVIWtGKjMg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
