apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:yw5+KYqgi+TQ+LHNITOUUEVoQDm8FF9Mp9JifYI0CI68wuS0P/u5L0+a0uPdn9MDUGzSQTt9uez35ZnoaB0wmB5w9do8XEJSaHpRvf9ow0TOADyYBsMSRgXO6YOUOjRJriIEaL3Hdj4FOESfUSnimQZY1zAPjie9U67qz0FlGh6xUQ0IXVGNtKLiy6PWIuDOONldpC5dPiBIMmU9pETbehd2uZ5h8cLyDLinoleGQ/mT4xSAM+Lyn+FiZJsoNBYHuJmrIIRpB57EIea+usa1XElU+46JEDs/SArTwegVFyVGmZ9SgZ4V2d24zx0zOnhEL+BYPuJHmpdbex+/xuE57JbnrsYj6bkH5dVn6nGXM3XGt5cu7p/QlUi7+hfPlCop,iv:n0UQ2+OlGE6+fWsYNFXO2lhTBAxu0QvM9bHkmNIBPGs=,tag:4aW6RWTuopqa/81fbP6XgQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZeTL9YyWkQ+j9h27oCL1FjPQZZThAPbsMvsbIvzVSxgym//z8c9iefY1jH6dOMujbsFYoFkJtunvtYKkFegaRko4JDOws0HdnMiWl6/exGYGpnMbzcLvCi7zYfSzLMj17/bqBS7BtXI85ArdlN3/xKNMY3ganRIltmtB5Q4neJVGAsaJMpXi414O28KmAc+dCehxfwdfHBNjsFjFymT/bzX8pl/Vf403x0K8Yk2iHO9aWDr6QpbJkWv8veQ1pT6NGnd36GkpsZbeol+8Pw==,iv:nt2DJstTPT6wSZv0SOCfKFmToCVV9Ltqomx2564v/vM=,tag:MSTdFiIR16Y6OGPCjJAr5A==,type:str]
    known_hosts: ENC[AES256_GCM,data:HiJMyjH2Wu+9rFgdy60NIs5HJhHs4flHbd8JCBYiJbYY9zBiKdITFxJG2+5zAcO+CES5UTXxyZinOw4u8dgX0ixR+Jv1pSPAAjSHDv5tD5YxOIBvzbnNzckuolRQcH1XdLXMfeVd2wxK/jkf/dlnKuSuSJgmx2PKWg2c5xpQJLls5WXKMMex/Q/7AJ1uUJZyaTphqXyrcwfGgxZbnuFRfVxT5QJXjPQCdl95,iv:XfVtvO5z4Lj4snIKDZbeQfvmGdZQ/Jk9+z5gJGqZEow=,tag:OM+AjmgFZNyVpvrliTnN7w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSW9vY3E0Y0lDOWtlWCt3
            N1BvajZHWmhHeXgrMVZ1OHdBN3Q3UVlpUlFBCnF2TXRnemVpK3NRL1BkYkFLVXZl
            N1FmM0hvd3VoR0oybjk0eWZreXNzZlEKLS0tIC9aWmc2RmMwWUJ3N293b1d0MXRl
            OHY5THZkS3J4eE8wbURUMEc2VGdJYmcKiYuNRY5zJYn/hIdKe8/6nOFq/pKXLtrM
            PIT/WyRTIRAR7CP6o5EQmcEBE+HQ07zKvnpsGZQJChbjqpYqUlHSfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T00:15:41Z"
    mac: ENC[AES256_GCM,data:mo5qBHJmWNk6NzAzFBawqM16AaGefW/aipVoP5moDECmMC1OzoT7JcEgGG28OIm0ZK2f3D62f0uMYXv0gNEK68DUPKWryA+KhWY0q6Y7gSXo9V/Zn048hPJjIMFonHtrE/8qYCPP7jgcIh98Ns1Qrat8iu6wOlXg1j/aB2PFN+M=,iv:TqF2cslJMvFtmln5s39IofAtKbqRHdnk5aiYeY8rYZQ=,tag:WkNzEwJ12aTPQQ4nJVq04Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
