apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ZAHXA71GYT4/lowUv2KaqUAs8ZV8fqrLHOt7a47XgV0muK9peYHT1Az1GlH5bJtka+Xg98PVNfc+EJrlWKJFosPMkhazju9jl3Dv5RhAHsfyGjscBd1qv2rgvhpzcYvpOqK+el9L71nuBigb3uSmIg3F4smlMn4i5cXWujid7xWZ5leGMllbaun0LocKJNI6o0bCJ7fWzEvAWsvIasujWo1HsoITBHuHa9Y4UJAYd4QUniElP9yGGoWOJ2hKl4MH7eeHBnaBRI04X0zM3KWh8LWrKpyFRUxrZ/WsQX7e4wD7Hh5hbFxNcze2yqHGaaU85E/bJ3wzypqoWNaPJzTTqIp+hO+Gzbtp6cCgRRkcHECAmLboujiwbRA5P2q2QO2c,iv:9s3pklJSnv0HMYSjxhS0x0pcUwZq3kaO59QbME/ufbc=,tag:03K8NjaCMjAReHyBpK1kFQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:MDbC4riN93VkHMDOv3CC1iPUQAwhmmp0HZ86Sdu5VfigXRdwFYNrKdIHz9pECGnZJMtW3RU7NCQnoewa8H4/bnXwe0rKgRP2rH0jKBwDfG2bTd+gtFBU/MIcxdWMoqeHQj+COqfBq2ewOjTg6xNvd2PFNRNd0qwu7dfcZfaxdLivoBd3YXXCwcXm6mvPm46XIYfknw2XWcfcHMFGFpWWxgfZ99WhujUSN8bx/0rJN98oDercaYDsUJPTPCWzc6d//1xCW3I5X/BujpWV4A==,iv:yA3s+tU7PkNzW5w3L0B90L2uWzRdm9ALZavYfu/C9hM=,tag:aevYvJKSM6oxsJLnC/x29Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:aDvFIqrf9qaFrnAuFDCcyJYAooaHkvHesT9JGkUR0er3UYbT30ndMYUI+fr4Ki//Vk6EVwPQ40Pag8bV4wI0FrHzFm7xheFF6no9fW2EVnWnht+8xMQM8hCsrPQ0KVkoEYDksCTkAxq1Y7IryxQOuO0w6yCIc/2okGHwUxb1MDimXHJryuM4VuOMORFF+mibfKMYJJAa0jrQ/uB3cpvMIWgm1/4r6St3MEEK,iv:NkT84A1r4AU8NKYO79VbplO38iKTxd54l8ylxWMmlNw=,tag:i9VtNpp05MCiNCMc92rXXQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbVJGbExUU0RTTGU2SUdo
            ZXk5U3JuU2dyZTcrSUM1LzNVbitQTkFBbFVRCjB4UW9OTGY1dncvK0lyVHVXRUp1
            TjJDL05mVEx6aUY0eXoreml5dmI4K3cKLS0tIFYxbXQwQU9EZE9zMk8zV2d0ZmtR
            eThsVVNhUnhPcmhXSHRjcFZ2Y3lEVUEK5Coqh5osm67FbhFF/HbVGGGQDDv2nNsq
            AjQcEgAZ4EmWKIvadQyWhj/0D4XF1whBHa60UdAQ1mgmUvOXRTBxBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T05:12:30Z"
    mac: ENC[AES256_GCM,data:FUmLlxzYUwRhYaFpprDLtjxMO2ffSqDc1iPLBrg8cdlytKRuh3HZ1GZwRlKlsikRAjMD8vYSSRvelKGhsW18W9dMmHV2JCW/SnItkKmgw1A1SFCHimYrqks/ueXrr1PiIRFqG/lSuonrMHapKk7UO9iRFKBhiFHr+O0K6e1BjPA=,iv:ni6V9BxQzNUtZkO5gQdZvfBpbwClG1Vmg0BEr+3oyvQ=,tag:GoDg7S334jkDaPz7G8QyRA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
