apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:oiYQHUs8o+kJCx551rKxkdihvXse/7d6X6Ug+zQHpWo/AO2eG2jFYi9lVz1iro63C745CQ2H0TvYK6mAWPJ2DEeJiyQjuwYr44wMfTOE71dDaqsacgvV4Q50xfWr/1IJvsYqDa+lFMhqXwghcxvV/Ee9jLZ5PraEe3msS2jH0OVBBMKoPNG1eoMCoLPyVB5o9zZ4yDZVd2GOuN88zTZSLfYkuHWyKXrtoGYRt2OpChBY4Vb/5gZMMnNxtkt8qiybmd67d4bmNhfHtO8qUF+TVyVEByebgkQsnZ08iLv0JMwaM+AsYNPUDyYn8dZsdSF2cEljHNFZr10PE+NMow8SDQyLgzwrcV6clb0zUZnNw4DJb/EA/2E7dz5EgOBysCFD,iv:y2xQ0zYldjf08KrRsHdlcf3nLlIxTOwccRpTH2fDFbY=,tag:yw7M32xg5PPGMvzKvvF2kQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:dTv988paZWQt93aZNLbKeoRe6cn1Y9DDcPwhfqAz9/cSfDiBIoEMCawkV4YrIo1Wurd8ao8JkSXXaxrPQCOlfdTt4jV0Pq8iISN56RhWBq+TMd3fHhjZOp6T1e9Zw8inTerAIcL71DzYbSCg5E9r7p2c4zsugj46s6faI4E+K8wfHhssAGoPWN9vtCfZd37u6Etvv4zyNTOyKkAFZ2J60VVsf7Uj7wXFaH5a6GcKrf7DkP5CjEIHGbdTtLF4IAUeXMVUAJ+XCdm5g+aVuA==,iv:0oFSvlCiNIubKzbPUlDkrRlm/rzFJgVR+BHUynA4RR0=,tag:p3IQgH61wLBgeD3Xledk6w==,type:str]
    known_hosts: ENC[AES256_GCM,data:4DFBdT+8Sweg+EaZhNRb1bF8ErOijwwcEQE3WfqnPoMoeLa2EJ86+7mTJRgou/xD4Kq0hiqQvj5cJxrfP1D03XY3FpIxekzKJ00ObYa7TikB36ZS1Y7IN/XjtVDuQnUILc2wBq2xMZnTjOZTKCc/OtDsrqtRZgFzNzjTXzqbrdI98YGtIl/joPTld6ROuv7xmX5ZiP+JuxsUP9PzrrMpxZma077CDQLhZn7Q,iv:h8/YukkBvlEmJOtMBbgB9IX1KVoGeo6taBZ/YIQ9gSo=,tag:E2aCBS8zX7C/yGErvEc/ng==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPU0pZTE9tN3M1RGdhSUlB
            NGpkU05DSEJRdmJkajVjR05ueHZqSHF0OVJnCndUSEZ4S2FyVUpONDE0dVpVeUFk
            ZHRVRXFicFR1VnhKUGlaUmN6RG4wS0EKLS0tIDRDU3lyZzV4T0dMNXA1UEh1dkwr
            YXc2MFppZVJhZXdGdk40cWlxYjc0bzAKJwgH/zcNAtq6mBYW5FIaF3ujELhEg/Uy
            D69H97QAvtNyEQSr2dyX9D1lhHpO7vJLQnIQDOeW3XQZUFYJ/fan9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T02:10:19Z"
    mac: ENC[AES256_GCM,data:gR+k2wFfMARRh1f3zJIOQH5PUqmEtqneXxXZXWDh7cFoL/u/9y/ZjCbUe8XwbzfnkJzYmNWPX8rbfEVA5iV7I8+DP2tIN8+DdCKOXNH0TnEAnftueg0xEooQAShyXIhPyJPY6JPGZYSczQLzNeBjVamejJivMrSXoN/2JirzCJE=,iv:oJzm3Hh4lL1H1UvSA/3cw8ugxZ2B8K/IU40pHiLr6uY=,tag:pqYLRGvfhNpLHmawjW0dgQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
