apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:T42Bn9hzDQa8eVQlwiiYOzOk40cOBgJSd3MzcmxBGaA3P8lI/Rjv1r+4zvUBKlK/d/WU+XjgHG35OUBXNlpQLGQwpCwwc8k7v/cXJjTPj+a8O+UppT4dkvnhZ2GaJUrjKDgg0cd/ABAKIEU9l/ecVvgmjt3Uew2fzyGKfwza5DbL/qpkxjxAIHd3Weqj1dfsWapcO1kQx2pnaBGoeu4wsoGkWyS1wS6xc/xjHtQLGJ/mcU+HcgTkIvx370hp85KPeOmrVJvcSz1xfNmZSl1ovubW+2XEMmHNFl37KHV6b3IEK2gW9955doCapQu7qlG8TscuMMgs1Q89/48Z+mrhcnZyKSO6pDk5qwJvKdCHRgFV4A3sAhytV5lCxWdhDdRm,iv:2uql+bzyDuLLCQWYt7vD1KXGd4/9KQlAu/lX8fg8uuk=,tag:Hwx8WeChnm3eKelt/OMB0g==,type:str]
    identity.pub: ENC[AES256_GCM,data:3wvkBnQGaG6HCcdPZk+ynAYUlfs31penhbiBOD8CcKzvr6ELEvSLUNBep6zy0UWjyIPImeXtSgkHxoIshKRamIcaF3GCgQEnyo7jNnzifOoNwBAbVxtG2CwdbyAar71qQVN26H3VDifdH+l9s63peZARM66CJr90hAy3dbGHUJ2PCGS3+Ej8RHIq/S63YyjYT6aurZG5n9DYwmrbbBT4Ajh5LNrlNlxmltA2L94t1Rv1Rwu/nRiQwkFfZyCi0RQNcvlw4vKVB7bnPhn3cQ==,iv:Jw3sRjBoxsgyK9BH0if9nNIsPiiV8Yhm3xqsHq8GU1k=,tag:EidwCgYZjcYJMj4RBdj9ww==,type:str]
    known_hosts: ENC[AES256_GCM,data:vHd5Z5epjWuyXoHPrHhEua3urr1Fw/OkU+bMQJT49cdE+m1OhKH7xE5TVd5ASln0sMsxDvFNZRlxdhzvRjuz+5awdgS0/pt2+xo+TmBKv9Y3XnxxAD4Dun56u2TIUjYwazc6wgVYvHLRGMhy3ll61YVm5SDhZHseMt1eWzZ+6vCHFpMzB6BG82Ub7elq87LMCLfzxQnvwKa4g3sz3UdzYfkj/lIudD9HcbZg,iv:HXtrkK5uyDFM2w9K96ShV6bFd/wyd3l7tmFM3fIIhRc=,tag:aEKiUWRJNAxIRYkatUc4rQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGL2ZOdkNoM1JVZUVMcGQy
            azRHOTZ0dUZvSUNWaVM3dlNkY3d5cVNrT2k4CkZkVUVQUkpZejBIZmNtUlNUQXFH
            eU03UVNVeE9Sa3kyM0NuU2Fmc3IyZFkKLS0tIHNGMTIxdThPVDN6NStOd3hCQ1Ux
            WGNXVldvelpFVTArMU9KSEkrQW1hVGsKK6GgsTupe7FF7tLmWjqt/BRSS9asNIAs
            Xk6pN9+QGkfrfQfX5HOZiimd1mV8VGPWa1WxEbTiH2Felj4QlPN69A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T01:54:41Z"
    mac: ENC[AES256_GCM,data:YNMPgjBCcjKJxlnuK3dGh8c3jiIuWf/XMh+wd9ZS0/L04RFs9zpG58bz3M25ugYSCw4jRmMOE5Ltd3FmpsxPwzJe7oUHiPNKmEm67/x8u9pzVHkJ+jDPsHs3l/qLOrFPj+jffGxj3uqMuR2+PUgJrofMinMIbLMKx1xpuf9wrhM=,iv:eThEE1vjGYlyhkHJZ7zJwOvRck/MXowJfC2k3VAarRY=,tag:9LRzxnnUSeww+PZ5o2R1Ug==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
