apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5DoXHfx8MJw/gkCVnTQ+WZKYky7cl7gV8yWsZ51/5KzdkToTgfYOQ30IS1xz5sD+FMoTXmWDychxvVyadXM5UJA/fQ9GIRFZLTAbaQcvSGi6MrOzF/sET4RyJWhEcH7SbVf6Y8brL88gdq5Z9t/9XrelFn4Gpv7ac0hJVyT0AYlCKoRDxrCbmufcXM9WaedfwujET5Wo/j0vU8MD9R+IIYwt9BBxLlkadlL/AYwFuElgB0NKbsBHXegiviBst7IS2/Aw4ufT7/QLrxmCZ9ykmdaaZnH9k3PencYgRk2oWL3IQieAuNuiSmcWsL/JrwdQGV7R4UeYRsSHcvjeUfqC5nu6gFwYXIji6CMbXX1bpuCrjfnsUD8PDiocllAbOMXK,iv:bR4xwKgXPExZoJg1HiQO8x94xNNRvjdzZR1gAnjGwDk=,tag:rkIysxBPsLFy5NkyG7OGYw==,type:str]
    identity.pub: ENC[AES256_GCM,data:+l2pJqXtroIWnBRPs/h8sHlT0rno1P5SMUUD139OfiWwsSKAWnOceo6kD8W/+JHActA4/xuLj85OZprzDWuCT+OnnsuZGa+3mC0xLTJbgZQbzdd6E34zFojPQzvxh6YfpDoOZzOiD1xO68nLPoF6kYS/ii4nRVYU6yb1craZ9zrzEmTi8SnNOLCwS6p0I4yVJ23m68jhIbYTkv64oGOjpWmvlzbTfpKV2BXlBQ/j1dUUYBLZ2eBeI0BiZ0mZrtX7ZiiWB/rntffwdvRb1g==,iv:vBUKfPFPB6B9k7+dHmbXqFs5wvxV1T6b+/X8wIQdyCM=,tag:42tZhlUaYefhri5eniQo5Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:1cTZTwE+0PJbPY+ZBcdXhmsihuaJgWsvHEMolh1LORd+RTwYUzIoVQIODON+Csk1XlHzFFYhPX3kk5SJcjlf/+j+57/u32OES3s7tkZYaK3azqA5H5CT5Ag0EgE67D9x29UC/n0C6oA+m0oF2GnY9DYZ2+L9PAQnx63fylxHhhj8qvk0De2TC8TGisFFLKpdQHPu+OqzpGn8ZMg3DFEjCKXft4L4jSRfNE8Z,iv:qNUIuqXTWqNFIHA+FWbtVIYWx6Qap91KMngwbVy9BOs=,tag:dkZvJLV/UDZu9MN9kb15iQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bjY3LzJXMmsyNkVndWRC
            UStGMmtGOUJlT1pmUnRkVitFNzRaK291UURrClI5Vm51dDFLd08rTEJSQ29NVDl0
            bUo1ZlRaRG90S2JKYnZSS2p6OS9hWmcKLS0tIG0wMnAvaGNBclk5MU45YkFIcU4w
            emdUOWJjMkczVERCbUl3YmViUFVYYnMKth5BDYhukYpfapeRyb1pZ6F/G4VH2jkw
            30UKzF4FQHLt5JFa4xK+KY5y7MVCJYAawHi4RGYXz1FYutZ4sRtP7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T06:43:34Z"
    mac: ENC[AES256_GCM,data:Yy/b4it1MrtRJ/1IJcR0grkbOLcn/VQMJXxWYtuwvL5GcJ69qCNm3NQKudTCXJaMMix5GHoAxmMGZwga4/Ij0n0Yf10erq1TnzXmkNKAcjCXMzjJqkb7U2UDguUpz4LmD07f8Ize3JvTd67E6jehyM5xXobGLNSu5a3mz8Y2QgY=,iv:hrsS31++H4SsWL+07ifxMyOtMpqgIcGAtX+uBJqIsIU=,tag:WaOL03e8Ovszn4zQ7pAnWw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
