apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:2t2pywyLAnW0+kwX670bDpXBrOrUTzU00p+ZI/hs1eJ6fwDp9mKOrb9kpSenIZG8BzEm8Y1bqjQ7SZqn3NgQUntdfRpXlgo7fMLXyGZ28a/6kDrfcojWyrcYr2WXsOe+/3ppQNXvf7KtLmWq6dpQHIrFVq3BgR4B6gLWAqFgFOcthRZmflcVW9A+Cd0xMVuMfj9ZSXSLEus0BUtWspRdQZcQnM+ytzcKgt8YTZuVKdWFWZRIThAkrRKzCO6rShgz1fyodDebRscyHtc9+p3aX8hSP9RF6iT33o3fKj6MfoNjcoqKWctX0zZWgTpKADDBC5vtQLuc+MsjhElEbDEayEzM74jp2Yh4538efhE+wzOoMSW7PIy9biHX086Qx4A8,iv:DZkyG31atW2yRnmvUwiVuaSS1yuCNNw+tljzOCB6Plo=,tag:X1x/dePiPxIhWeWeq/0FJA==,type:str]
    identity.pub: ENC[AES256_GCM,data:zPhj+fn9ezMjEP58XGLT5dL+sPj3bpYYwmpZmiNjndJqgAxp7yuTFW2Bz0rMO53QWuNLBiO9vIDTy+++1PdbFawSAknTVveVj0qV8WyNctVGmNOnCcBQW/sEf9xFPXRXRfHgj5aJNgeEr/pH/rdtIhN85gVMMlpBExnEPGXjEhSst+ELAZcuRlaMPDYO5uFKlWf27Esl1zNu4CeZAdNd9ApNKv+eCjXxwQcRlCZ6/pEKsv9GLTpPqggZmFKQmWF78+Bgcrqk5peZp+Pu0w==,iv:LU5W5Oo9wdoU7+suzt3Q3oSkuV2VecTcbtd36ORPW8E=,tag:H6+TXjqgscX2AfRY4r9tzA==,type:str]
    known_hosts: ENC[AES256_GCM,data:7w4n9r2hGAVFb+XAZrpyKZG7cpao4Gm2gugQOVu+Y+Jdg+aLajTfGYc7hXZGpOhk6aITofwiCvLWNdQ62PIPMAao8aTnQpK1+z1RUEaB8wl+RKyfLtYAkLbV3nFiTLWGp62XIaz/0IxlCFPPG47mSUXkoqGH7mcKk/wwRPT2Gnd50edxJNwCAiZzN5s/IzHn3dxCJC5ef8y6pMUHa+S/h5EvZ7YsW3oVm8wE,iv:pAYJR9lAHGAS7L+8u/XRdqjvqjDByY3tKJii1/s0U/E=,tag:5/cI9BM1Jx5WooJVWWR52g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQmt3enJMbDE1dFZialgr
            ZEtSVUhJb3E4RENwVVdpNXBZOFRFTjkrTkRBCmRCcFY5M0VRUnNUT0h5UGJBUG5a
            ajlEclRaRUZDQlVHaTZvTEVvbVVheDQKLS0tIGc1eFFxUWNpcEtXZEYwdEpBWERV
            d2NTUThyWW54STRXbFZ6a2cyOWFaNDQKa/Lv9/aD/c7NfvGGSGVLklIqBkE54A+X
            GebGQzfdVqHnibfQQhquYWs8I+8tQi5pIK7TRXNRe+cRlK2snBBDWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T20:56:36Z"
    mac: ENC[AES256_GCM,data:78ZGp3Ewm03JKN60+/6uHeRlwvcogqDcN0J7EdhDIGtWbRvJdNEbWUxYHd71XpFgKeyqTHHe0TwJt51KiXTyHliJ0S8SGVehy3yWeBhKYJk5XqCZNbrC2FdftDBtnVDGvOji26Hy4K6bu4NjK3dZ7SEHw/+wDdG5VqZ9Zjzhr28=,iv:y82LPWGb+hTtLxffccOGE9o5Zsax+08Y9O/yIw8d614=,tag:WAYSRpsAnFc22P34G+eP2Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
