apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:V6K/8RlcOfb0Iosl07IXxr7h0SM8Wj4qecz7uKRr+cgRaSS/wmw0rcu6Tee/mcqxEnStxVC4wgC//DRKuEL6IOmMEVtVqlepVmJlWaEPapgxDgh6y35vH8B6sFDRAeNiLZOdjL6YC/jsNb/BHHrd0FZF8HQH6XzALu8W1w4CPqhMLz/McZIsPwi9Drp6nTG/GtyThl5OI7ayjjMEuXci1gtB2KH7ahuwMvuBIB+elxf+5xEuGF3K/NZED0ZlbRxsIwOq0XTAMbUSgTBpvocHlGP1wNcyJ//La/SYelQGzA28udgvQb+Ejecdc6sok7LPC6DGj0/o37zrFsYO/LXnhHHBVrRlyqxISFsdVFnssJa96u1Fch4FUQU/gOhfDeeT,iv:NjZKqYSHEi8irjCFmMWdgAfhgNP5bTdRWq+W2KK19iE=,tag:mbIA3Q24l8RwxocsTM5dPQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:HDLV1ePz+ehyr9l7gOwU23dTvyQcKfYYAiGENYkGaqZ5w3txHthiWasN5tmsEocc7BT9N9gezNCWfdFDhwMfHcnhQdCGymSn/wn1ZJpJIJgSwJU29R2bAjQZHp47m5OnWx1mKtLeXPm9sPrV+gYDXa8m7sD0JIzDHHD47jg8oFjYPpWCt8vKb8Hgz+GnadXrUXis0gfEfJrW1thoZtSTEp3eAd/BLJ4jH3LQIROdjVWfxIbjcrfT4MWb2QjeEhKTUwJBYNdT2w26k6544Q==,iv:D1jsDq1qPTH+gcItTo5Iohd254SF/cQnAWQOrruH7hc=,tag:G9uVyGyuFpMjAVq0ZaGotw==,type:str]
    known_hosts: ENC[AES256_GCM,data:QJLnSpRPkxpDdKf5+RdXleuRxkRb1oZrP3qWfn5czEmSBGoWu6InCRYbEcg7xn2kKh6L98Njlx6gD/IplqiXdywlC0Mi/SpE3PMfRD7nKSqmUh6sL63UWP2pP3VED6yRuBaq1NHh7A3zZDRQN3b5d1y2ygU9e6uclYB+v+p1DuGtKSurCB6vI7drmpw6cgJIXC0Tqe/E03HI3f/D5jJ9UI1eCdyYqoJ9+CY4,iv:SSFhDtnRK5H+jQWNU4keQ+RKFAqajmFnWYgDHB8IELc=,tag:y42lDMB7AUgMuwVoUFHYzQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuaWNiRmVqNTJYYmlJam9Z
            dlJQV1E0VS9CQmpNbGJla0krUnozSVJvSGprCkV1dGZrTDVCRStDTWdVVDhLUEQ0
            S1llcEg5YXpxSVlHd0FwWUFHeE1BRTgKLS0tIGFwL3hHZWtpYTg5SUJ1U1NwYVhO
            OG5PQjJ1R2VpdzNHL2U4akl6emI1QjgK0uoExhtyvqA8FHFYq0yy5RhW45TD9A6o
            1AI3pusvPmerLcyVtv9bx2MQal2JoUEtA4FlCNrnnNptitgdswrwBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T19:54:50Z"
    mac: ENC[AES256_GCM,data:KVtm97LnpU1xJ9UpPahB3980+Hn14ScsmKJO4iYpGrca9+Dl8JV8NvcgHbjP8tdbmCvRWBKVBWvxR38G8szjI2xEQdnQ7jUvzMInoG3Q0xohqIHVWdNYjNOnjs945DdxFvKIty1hzAhWV17pS1xpYhnr1f7iyh7IRTYKY1CCfc0=,iv:I9YVT9j0Hb8IBg3tvL/nbO1/At7OF6kNBnUatrTtGPw=,tag:RdtKALvJTSZTiivmTHRDig==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
