apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jJLij5Nga6S+19J+seeMATu1b2/QmmR6z54NCRMUca/NODif43qH8VlK/PtGqJWHWJoRnvea6vyYHynOVaNSEpDWhLUvbYFJ9s7J8QGhqcwI04RRo+jM4D4k5ikF7VFPMR5AxXaVZsykdhcyngmV1Zfgih/0I5csKsEF1T9AfsP5XT9tgCL7R/zRXsmUznYFrIH+ArHeR6JywEt9AaQBVXnqeD5p1RVytVS7WZXyepv0yuYsmBK8ZPIMtnAeOto1kX8lgfJWK5rumzH4GtRfQIAQhtVfHhOKAzf2aM83UO1tN7OqDY3XxG1KAaS4y/G1y5TNP1i7zcH2L+vkzlFVcDy7dkVGo/KgW1Rrv2uxihDxsgM3XDfWbqrizc2n2i8M,iv:BpLy8ZIEamihh1a2USMZWOg+LieWsQ/eA1Ep1kMR7KY=,tag:/2w/lrgW2LCkWF9B7rtZ3Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:lFACBXVQCrDogmUR8C4oT90kuScBZdosAI/pllCq11ugZ/XES7a/4f24/OnUKNRR9zMz/jhUpoWBR22BB4nk5uy9gT7BmPqKpKjnRJe9tBxX3YHN12/4ZBSsnknUOIGpiOQTBpV97F9PFRacoivYjM0bsMDj1l7lMY5fWgqVVIJYTHIKbPkrVoHC0HJNeXLTxLnKlqAeqknXYDwcspPsiAAA/t6SGqeBPVzXYy8X05siXLOL6lmUPPasDCmrKyOnBqSffEzFdf3my8MFRg==,iv:8aiioNw//zTnWmeEVYRULmL8oYasvsIutXKmPNKU26k=,tag:1y6QQDpHd6OZ8AY70P4cww==,type:str]
    known_hosts: ENC[AES256_GCM,data:PmVmHlcpZB0XxhzbWK/r2G0sbfv6AzMyqmjkF9OQ82DidaJI+lPHe1rRdLfIXPPA+SkI++a7hdlyjSvEnvhDY/ltJsd3KzT7nsqFV0Z4BtjQGszxVdA0mOmTrLOgVSd3RIJBt094qZpOkdfHTF/CsXZ1zeTeTFhmXFuuHnXetvL6ZS3afn3lDQIoCY3fGg+9DtPV6NPpTvqBM7JcrySLMOt1FxATiy/4nvtq,iv:wVSWa5ovBmvmY5k8UneUDtHVqdWGmyhiixufh8gnsEE=,tag:jxsNwad3aINUNB/rRvl+ew==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcktrSkpkcUtsZ0VLTDVv
            MTljZ3FqenVkellndExoVDJvOVVHVU9NN0RjCjFWZmpKUWt6OUVZWUFhcUdNQ0Fh
            L2E4N29heVdpUkZiYVo3aW82eFdHSXMKLS0tIHhtV3FsWkZ5eTk4VzNLaURJYmJt
            cDNQVW1BSm12YUIyMzVsazFxWXpPVWMKHNMJWUmxnvof6ufwS5OwBkS9wWWSLQL7
            V8qK9XF9yDLGJvMHdm2msE+KftHwUI0cfbVZ38gGeOBHsSzxNHI7MA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T17:59:12Z"
    mac: ENC[AES256_GCM,data:ZgHuu4n7GaHIjrVM8xo5Ei3RdEAtN6A+EsN8KuXe6xIKZQ8JAs6TmMWTwnLnMO4ti53ndtnXlSj22Va6p4SINzlC770fru8g6bKGBFeCbjlVcADD1GW+SP4vz3UKmiC29GICKV9eoW0ir99yQjaJzuCaw042T2AbOi/YKXK23OY=,iv:RrkywCPZN3dX6g28yVKk/HtgZyx8clY0H6h78JpbB7g=,tag:Y8pL9p13wZIRaTvTcZ9n/Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
