apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Okpb5D9Kn9n93zgYxLjPE4stZKGGZGHcv8WD4p0LRQQhW430xCuEYP0QIPJo0mW99f2wWqh99o0/Ip7t1qibaeyBCWoebZpg3v5yiU94c6akx0NZNowAodbvPXRUbe8qGC5qu2k7BlgpcvfiVhXWpC6fm8kQ0C+E6bLArjSZRXRqRrItmPuMlq/FWMob7Cp4hY0dWGOEw2ZFSwOGe7rF77x5U73VqEkI1ESHtgNSND8/ZzdfzPztAsUWfx4BYNpcQHhZiAc2hsnm7At0xwtnrkqAvGbM13gvIp7+noUe3T3F5d89A6PXxi96gdRbQxO8NbnXJkU8uGC4iRHd19gkZ6yVE8LlzOpRNESpm/H1FKuFRAQG+uFeW8clDW4m71b+,iv:gZA4jSJDGP26hA7dcaoAjMCMH/UdzY0LqACXWLEjSfo=,tag:sN/Ka+IDfEdL8LvgmdXpRA==,type:str]
    identity.pub: ENC[AES256_GCM,data:YaYyo1U6PVVSEhEIsUi6bpNOYqwnW2AKxNSomh0FKwy2UHZnJZLot/AppwP7FPvv19OUkKv2IeXGJSHhM73HGNd2JgaCjJ+tOpyNo63ZZhnMWaBFeN499mJu7Ag6i/kWdSCOCyHjnaZ7FI7aX0H7qczOUrzvOm58tx8mVUi3zYR/UrdlFBg5JYDuhYxmyHinxiQcUHsWGzOe+VNmfWMjpGZrhhx/+Xi7PJedCcpjYmPOCuQGhJqdBcpsO6wDKSixPbc+PpV6BknUTUh/Yg==,iv:gMzaOOVvvna+xVXPaebv3YeWg8M16YvZgpoTfGUJ/gs=,tag:m8OVi//LiSZRaRRvXpw98A==,type:str]
    known_hosts: ENC[AES256_GCM,data:sRkTBAqBy2BQIrfUJq9lxNwr37GXt45Fr26TRAk1Hl808XG1mqAjB/fJhfkq/Oqj5mfcDEeT4nLuNSty3vI1tEJRcOanQz4+7JEP/MKiHxcRPMHKVyEeD5+P4n8RP6jCjQ4cS4v9rF35JA96SvBtVhlTqqPRKMzXXZ5ErmEfTzbvVvqQ7WY5aD9+MTp7+Nws1UJzGm5TVOzlnGAAGNqzMi1svUttyYhyAb3s,iv:a9ER72N5t2OqHoP/cwIq2xI287OC68j2L4EC11TrMiU=,tag:jBLcNqJbHlbSlfnUY+Uqaw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQk4xRmI0a2dzaTBrMzBl
            cVJVeDRaT2ttNzB6YTVkSjNNU3N0eGxERUZvCmpKdzh3NzFZeWxWUlBFa2JQTVhB
            RlZtWDZRdy9FSzVFN3F0R2tKaFlQRkUKLS0tIDA0SUlOUXR0ZmVBZFFSVzJZTzIw
            RXJGRjlOZjlEVHZkTll5NEFvc2ZzNXMKHu1eZ4PJlE57R+gHKjREyQ9P8SSHP9s9
            RORYakAJJIdfQYya6AoJLUYkssNk2AArvZXVUFI1BO898k44G5r7Kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T01:28:19Z"
    mac: ENC[AES256_GCM,data:vJnkp35wbTk/uvAstUHMfBYxw1C75YnG7IoC2o1MoW2W9afu4LpKH1zk8VSWH2W3/13hvBKPZ+5wuGXGZpit/acadqN8ok+wyrI2XL6jgJ7VvN+/HEQU4DdrTvkNXErXfpspeDTn55U1he+RWSyP/otOlprqhzn17BLOkUwX2x4=,iv:wZCoUMtO4BA+fQQIK/OyT7EmAPzscqAeHLOJtde63zo=,tag:OwZ7zZQV5L2H6+wjvFLibg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
