apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:gYFAmEug9H6+0I6m6hs81kxpob9lXmo3M559UAWLdP8kabt6TaEjKqkkoMSW3YqpfacyF7q+IKBZ6ITWz7EQ7veo7oPY5WNtlkLEf8NPKs8VxQLtDg6Y/NWWzsvLRx8CAhW/dav6NOAwBu1JK6eQQ7Yn0yb1eaAQ/A==,iv:bB7vC+nMrc05x4cne7RZ/Oi92gxlg2V3tK6a5FbDxSg=,tag:U/ZgAeB+IBMi3LgnfXNpcQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSGxZOTN1OUxZdFRURmZj
            a1d0Z2FUZ2lXMXZURzRuOFB6bnhHL0lTVUM4Ck1nT0Y1dVg1bE53M1ljM2R4THVW
            eHdEVUd5Q0F6ejRuUERDU0ljV1cwbXcKLS0tIFZ2bit5d2ZPMlJqOUZscWlNdmFj
            OUZaV2ZkSGhoNzlNMm9iU09XWVZkYk0KbYlneo1mRp5zcNQG+T9aJl3boWPQvWcJ
            +YKWPF2qRbCsDfQZ7d6EH/vnACie1BtG20Z/wj9rafJ3PvtbOdQsFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T21:34:49Z"
    mac: ENC[AES256_GCM,data:cUItvkAkM1MKdXFWGm8dr0UlU8T72+OuLS2fL3zeKW5NXpCx5HTowSkBEOn9jD0JHUJ/N2OMJyyEZxi8f4ihoLQ4l/RExndhDGIaBdOU+FgZ4HD/Cv+XTK1VaQp3J1HEhIQ8bwvp7E6wkruSxGXcQ8Rfk+ShDmHXb/FqQoUlFRA=,iv:hVeQaM/U0SMyhTQuF56VS7eDxMEq8WEE3qqOONEL5mU=,tag:O33oY6xh77NX9kZBPwUB0w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
