apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:HKu2/Rq+PYtldyAGsIlBEpwo/n2ucncJtbT/aIGKeyyo7/c2HC+AGwGmb4kHPUGbiH9leuq/fBWuet6zdCHzHzjVNW8FdQEBtkscotV/mhjwLiJqX+Sdov5m7YOp7a8oH7gxdJ5JLAVeW17TYUOm004HU/Hx9BtB0Q==,iv:Up2bpMWmh7yghMPlWM5OqScrJuKIlUVjfD3Z92ppbXk=,tag:h4Tom0D0y2BkWQGsZwKK7A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUnRnSFlITkJGMGUvZUxh
            T2VSYjcwWlJZcDJZNy9oN1pRcUhxZU9SUzJZCnJxUFVTT1V5ck4vQnU3N3FISHpM
            d0JzdnBoMFlCTktDaVZvUUxLdUlCT3MKLS0tIEJuVGJQTENhVmhTeENvdW5Xcmgx
            aktyM2lLUUgwOG1jYytNOG94VHQ1TkUKgl4gYmAe2c3SjFfWcaSHg/ovDbgEyrc7
            Mn9HYwMYe1640IXfjRY65QVZzK2cXKpgaJ//R8++o1QEXq8sKUjudw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T19:54:50Z"
    mac: ENC[AES256_GCM,data:8cqZA6XPBn2Qo8lwJn5fD714FBtN+5FNgZ0QCQlUM5y3nrbaXTPk+AKgSs/2Kx3m29/a9G4rhdJzS+2soZE1oDSme/zs1dx5dgUrUeBbQMuZxrIsUPKEe98n/OFVdxdBozuuUxD2cLKt+OqUYucR6FtuWGSlNrmg4oqCXlKJ7wM=,iv:VDTyU/+uTOOthzyNbXNCEmh7lSiKe3C4sVkDYGpOY04=,tag:gFhiGo39aYPXvNVEVlKWnw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
