apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:mKKP8W2vUPf4a3Nl/1JBWTn8Z7nQ18fcp6LxLzHDq5GO6k68cxyPiJpED0kHcmby5Mmt3U55N9nt2BAzn39W7EJqXOPKL64AnTfs4j1x3UHbUnuAmHIyF0fPOJX+Z+d1lvNG7Nznz2k7AO09AwVsNC3z7D8CofjLLQ==,iv:tyOKdmmakdIdKsTQvZI+U0cF7dQg+oAtX2zESqCQ6q4=,tag:oDB20RYbmRyVXh8ECTTJTA==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:xK1Y0YxJgxXzaCWGe+huPaq86f6S+6eExH75GCY+BeksZo4BWDO6czdqqobvWPr3oN4NFDnfVDeIZRIIbBHjtw==,iv:sJ/CnydulT3+5Jk+A0++rz4wU8FTCL57sJs9UKXS8Bw=,tag:cy7lbm5TZ7q/0zWNEwkJKg==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:DNLU0NyotRkX2m7URnV6/PEIleLCAslAPKUTjVbS25RsAwNh66Axp9JLz1aZjjBa7sovaec2pPocAIra5cRhpNp9wLwCDiKIojgetiSgZGBuSeOQQQ==,iv:BUhcMLYzTQke3DfO/lcfCTAyx69ucKiBOxtwPPS/gEo=,tag:lc1wAAwgxdpmGWjLEq+4yQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcnBCRjBRZGRYYjZBcUg1
            YXU4ZzlIejdxenI4LzBEcjk2L0d3eTViNnlJCm1VVjUweWMydTgxWkVxNzYzU3hl
            ZUhjc2svWVNabmpiNmVqOWswTHJMK1UKLS0tIE00WCt0dW9FdSt5MHErZkx3NmJ6
            Nkl6WjcvbVdRR282aGRIblJwbVlyTWsKpCMAO/LtHefpAWSHKpTCDF368SNM4KP9
            D1OlyseXfcNNjV49ctrAYPiAHq4QVgJKjXNd/idKUGb5iIdzZ9yN5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T18:56:19Z"
    mac: ENC[AES256_GCM,data:ivuXrtb/qPE69x7Ov7Bkq9q9mfxl1pnhdbKbfdY9t8PIpU2SWvCDpQDEBhrpAHgZF6iZIJBOiOjeWOCsMx2JbZa4J2dushwl71OwhbirbY0h0UYUV1jwTiDbJ343HMa/3S2fU5kyiJGfObLV6+FpptnZkztuUH2qlx1qaGAZEno=,iv:SbB0OrOKmG73qHyxnhfTpMyPhY+o+Nc795hSzWmy67c=,tag:IffleG9U5ZCrx1PS/A+yYQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
