apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:7YHWUSJgAegNcWekAg6gulFGIsfOes1M1o5Ud4XMzY0hLTe9nXVE38MwDXNiJ78UyiBM3Z70IUMO2jQZf94AKsyQ8G2j/M8cxjnKRtOJnmiitigCtTbzE/c7L3QycsM/jTbhjLG3pVBZb3QA4ClTSDcSfjx25NiCmA==,iv:+wcIgf/9ZUkMvWdcuTDg9jSAcJ6Je+CC6+m7JXjOvWg=,tag:7rc09rDrM6AbTYxORjA4cw==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:RyMXBaPiiiGSAdOEE7FC7ugo2FNUKQu8Wg7N1LTurSi5OvLLw9pH+J+2T84H0KzhSMbwPlLTDcwjsxY2ztH6Hg==,iv:MIJ6MU6FM+bVTca5gGB0WY3Gs+5kAgallMG696Cg0MU=,tag:olGATNiiLR4PMHx8k7zPQA==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:ubpRbCpxhlLiegoC+DTJiOjd9SbXXDjMePeeL1MuFv3OI92F3GnSYn/yD8UgtEr+UjOtkclIa0Rju5dATWkDxdJ23ys0IXztmq8VYW+X9aqQGjmMeD4JIjOB0f9n,iv:h4Vr+mFfNJF2viuiVV+BovRQPJEzSuzfy0OxHuh2twQ=,tag:/mksOG+DBvwf4IUJFY+8Mg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdEJLMnVSWWF3T0xhRVJD
            TVZZYk9Zb0V3RkpxczB1a1FtYTBiQ1pBL0hZCmFxdElrTEIxc2F4T290NTZJQjlp
            MlcydTl3c29kLzR3aUNNY1MrZ0I2UDAKLS0tIFpwaW9ySkJ4L2E5ckN4eHQ1SHg3
            Z0JVSXdBUTZtU29sc3JxbEhCbDM3dGMKrzaEqTrz1EDADED7P1tJ90LCcN2R40hv
            eP27C6DGsAI+I1O3+t18Tobu5F7l+vqhI/zNtwd+HzQcBPRUNibiDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T05:12:30Z"
    mac: ENC[AES256_GCM,data:hf6uWHpc/uj/Yu2yLn/GOubgtEIMslFBWEE9E2UdLHE+qlF2Rw410ru2K8rYMB/RtXGqVUZmJf2cgU6xl3QW7I9zy0s0p457JN0VIgympWsF4ymWZdBeJekhMr2i5rk8faRPhJmjCYAhc7k+qpdIYJmaU5ZOGk72A5vlmviC/F8=,iv:PigzuW/+c/tIDPD3Fce0SC+H2hXetWyOESBQ+vwoEYk=,tag:PObGr/kn9thhmzsfeaxISA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
