apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:bPX4o+og8JZvn7Tob0F3wfHNHCVK19seyF3OvjcC8p9n35GSb10STEyrlpbJe+1XkSr3GEcWM/6Tr+uGf9QVETlovwqWLkw+s+lLBRPIw0yzm4DSueqlicuPpwOcDkcILf7u9GbLUGla3Z6O8zffnf5CTtBC8DMYjg==,iv:6IDod1n+Sc8xsHmf5/UNomd6xGKDufXVleFyVb3CD8k=,tag:i3FaKpBHLH059CKPGuDMvw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTkQ1elpuUVVraXNuaW1M
            RHlBN3BKSmJYRTBPdDh4cWNlcVVXOWs0eWpFCkdycUFnOTNzS2dQbHkyNG4yYk92
            aWVBZjl2eUFDRVZ3ZkxxTkFpaVFDaEUKLS0tIFlqMlR1TEVWbm9JR0JwdHFaVjFO
            VUJxTk5ucjVpeVZJUDVvZ0x2NE9TY0kKg9aPUn7bGlxP3kt1V3ozAiXZSdI6cXCa
            +uaV3ffCacsdkzLiIkEKQQhtBjWh36PgIo5OhSvCsiUbdCPZ7a3KCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T20:28:59Z"
    mac: ENC[AES256_GCM,data:FJJ7pUhi/qDdRU+/7Lg6ODVUBRoVkzaGba/UVKW0eFSJGVqAn8dCJQQKzlG+kf4RoJDOvAwrfbRXTy9TDJYD8P1i+GDekibA+6HDFxh/JGVxGkkFH4JzexJci/96Tuhm2Utbh6fP0GumG/7fqZgO1qD9n/jvzeMjyzZjYdXCuck=,iv:7J5YLfD73Fo6kssJgHMpiDVDb0PjHy46MmIVWwnK9MM=,tag:G7c54CnDk/JI4xJFQaUsPA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
