apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:DNgRjyhkYQfMVjoSX0ltrlAGSRWZsHPQ7KGa3CnCaMOlYMWA+8ZebSMK7ESJnchEWGDfbhNIGzRbzssIwwECeNEryCElACgv4+lmPGSoRRRS5PZlgSQqN4djZ00Ioah2W3U54rNQ85QrD4WeCHRQ6szNHR4psEBOxQ==,iv:CHxMQmvndv0ik+Bfg4OJ5SrfitLoAbilUrl3jDve12Y=,tag:pr6y015war7GU5DUrBXJdA==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:eHKD4DvlbbU6dwQPNJQ00iz9L6gNQ4I6w3suGLFpdvt8O1VBhGBPZE//JLjK+JoxQ0r1L0RGPrRfi7PEtsuf5Q==,iv:duAN/pIwAOo1emBeNwARutTTb9VozOmC7KKE8JJ7OCE=,tag:gGgP7jm87S+FHj7G+cTN8A==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:zZ2bFCvpcBcvaLvmmKPabcv28xHRE3ZUHybyJJVU27dNZrD4+yI0FTCIhFx/icyFIpdm/MiVrd2leri2LzlUMTwsz0Ipl+1X5RSz+yencdlZG/z8vJWl0fqti+BM,iv:oMlYfgR0vtmZXufPW4Dl7MQ0ZQRLNxGwDig1xoLVW+A=,tag:6WgMOi/rGl3uc6sf60RCyA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYa2Y0SWh5VFZYS0tQYVQ1
            cmV0LzVZMkhqRnFPU25hK2N6TENsU3R6d3kwCkZpVVViVEtua0N1T0I0SWU5dEc1
            Z3QwaVhRZGhHSCtDRy8rMHp1c0UweEUKLS0tIHhmcktKSFM2KzZWWjRqcXg0YTdJ
            VnBRZzE4emZhZ3Q2c1kvaUtLQ3BzcjQKno0An/2hS49RJLUbY2VSq73OrpD6xtxi
            DJT8ZwtvPA0jb+rLUdN+9EOqdNWe4UHSsAGKJ6LNFBBtAWqvcO/yEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T02:10:19Z"
    mac: ENC[AES256_GCM,data:whA26Xs6ZeOseX+MHDoMl/In4jZy6bke8lWk/RLqVmyQPRJb3UQWBPVJNsJHJxELwpMj91qqMfthCzLRX09gFHOiNV9zun8yuWexiwatW5cy60VdjHBWoID3+3Bs2s8tRAtSgh80QAWABmLpqfjqa9oHV0K2w2SP/FKJAak9B6Y=,iv:DVAoltzZlIshJjIHt5ORFw8gplZQ4K6VGEQ9G3BnMEI=,tag:4jJrNjsOe64usTVF9jKuyw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
