apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:mcbi8wvMzGiFQNFGfuy1AuMpMz048LF3hIofGwS7X2PmqbZeKMtMR49F6sWrW6XV+HbvcNd+uXCGwYltTnfZMaRxysWoFjPeG7GWM1lm6IJLjaF+kpGCLOji7OzOwY+qwCm8HeuMsAVAygeKsuMtTH3Ii9bQWbVm+A==,iv:sgIVgaCxvuv3H0thTDBH/sRfkbH3aUySqUEouWkhJdw=,tag:kvIts+afPKVY3TQBBCVGDQ==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:8ewCSJpLgbB30gPfjyxVWCcGwu5AvuoVgO/0MWdgYZyMg5HxWbpwZAZ8BuP7blaeUkqfHWEXHd0zcNdsrCxd6A==,iv:HO4Y6eXVFrJIImDPE3dCkY/TqtHnVa+Qjq546UBnpUQ=,tag:TdLyMduvSHeR8MxVd6JhRg==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:RqhPzpx28LV6CxGp7F1NbsyWa8rSf4yp3zHhsZpvEeq+G5otIwtg29wkwo6gcSZyQHfACJvvbmtyDyVvMroFqcvDpQF1r64FLAkwsnNp8KsK5KwZ00+1MSEaO20w,iv:pmuDxIYjISCq6WubOwTHIEdfgPQSqBtIeeVE3fqoDoE=,tag:MmWwHywsZqzs/sTZpRwWrQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSXFLWDlZa2RnVEc4WWJK
            WVFaa3dHUC81VFRLc0M1QW9Nakd4SHJMbVc0CjJRc1RhajQ0Q3JQZjJad0pQUXpv
            N3FqRm5IU0luNjUzMHZMS2I3ZFlXbVkKLS0tIDRkSDdUczFTQzVQQ1BaZEMzVzJl
            bUw1SWZ0TDNkUmNJQWxISGhTRXFrWU0K6aIGF2EfcDlAOovAM3xq6d90LdoVb+iu
            ESvFxn+InVFYvmN6JJeQTYEo0U2iyX1KnXhr9QRRJbLMzQcSDfZjHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T20:56:36Z"
    mac: ENC[AES256_GCM,data:HS0chmuwopTwsXwb5XJcdVu1WJNvKCshUdu+xkYo2fWv84/8DewRY3HW9eT500P+hroAUXXbm3Klv4oBvmnnBlqseZUcrI/BdW+84uV0RRXNcq8vYiNQ2IosfcvKXREzpwxha9y0ouMXLZp80AAhTXPOgKvlUbEEOKGzi/Al7fY=,iv:CtQfru9km0iuV8Rcxs0I8i63ZUU8K3bJ/RxYK+8QaD4=,tag:6i/HSku3+bGZpjAcskucBg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
