apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:AFCmaIl6nyp90MxhCY+HIkaEVX9xuQgXuioAjRtnFVUYIl3JVP+TSY2+4/YSAUZtEaTZMYeiz/NOcPBIeo9ogo8rHhmrQhY0FElin72WkKmEjm70rpNE+fimLxrqrl+g3+bgG0+seQX3DR333eI3NhncWDjCfmh14Q==,iv:DsNQ8MQAAC8mHU31xO7J7fq1ANYUMFUZv2oK47mxuYc=,tag:WKZDQWy+wYW0B2kFAFcD0g==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:isjBAZPr0BEYDWRoEpssQteyEUQu3qKs9dZtUlY8CjmITxEI+jbAqB3pMD75eukNNT/u9QrVFIkVgdb0f1u9mQ==,iv:Tn7lZkv6pTr8afGHLYCu5DFicbCW1asM8ZfJzcYlWoE=,tag:b25+ROacphRWEUTFx0RS+A==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:MsRFUWCJSCaSfT6/XhK0PKEwOFD2OgokiaM9hwzYvoQT7iVkFcOGFwz0k6vhFfThpOCj/L+ifrBs1Sp9oFOYbrlpu146KRpmK//w1m9uAuZV3XY5Cw==,iv:wLIK9xMsH3kEsyeGfvor63GtsANlTB3TgIzTW28H3jE=,tag:yL9ISdV5xd5ycay/dyBysA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWkxiZmxXSUFrZUFWRTFI
            dS84bTRzNmdIdnlZY012REhMVFJZQ2RmN1g4Cmk1WXc1VDh2eWkxMk1JUmh4UHQw
            MWZVbU0vdmhXYzh4MjN0c0c0dWhaSTgKLS0tIElzN2tjNHJzaVBYY2xsQ0NHbi9s
            akhvV2dUR0lST2FPd1ZLVGQrZmwrbTAKGp4LpGHUb8XlttJfpyCXYLkOb64HqrzK
            S+zX2AAcJnhp8I1mkPjmM8tL2tPsliB4FEoIq4GFfC8EKZxRTyJR8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T05:24:07Z"
    mac: ENC[AES256_GCM,data:xcLJ7rLC9E6BxpYgNCCUkB9ZfI2XeKS+R5GT2AR7u30Un4jq8EPxysaXrS+deNIZKZ1EHEY3F0D6A6X+GC2KIJ1yQz/s5krKiPfZwXN2oNdC2+SzrmAaqXagVIPYMZ6GpTRyH8TQdWH/EjIsQ3meWKi2r9IfPyjCal+gMzkdYNc=,iv:Q9r2pAZcJdvu8ualxc7BTSMOg/eqEi6GrZDVeOP6Qv4=,tag:BHlmoHKXixCdi5SmhM0FNw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
