apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:TtTxKQmhnUwBLuNmm+sEL7VvpN8tjvws5Dke7++TC7AtYMJPVMnjlGXDFIlfajqzM2OMU+qTXxATlvUhGEQaXijsNX09TuaesRFb/iS8LBeMIVloHsjXEC4rOV0OpYUyeWZ9jRBZij/ddBH4oP0SoLUDw2OoqmU91Q==,iv:wDLFaoyR5J3zSrXq7w2ZtVvgtFeq8vurXlhRMY9q+sg=,tag:2Nkvn8e1U/cpTQxy+6RJ4Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQlN2T2ozWkkzMVpFMEg3
            VlFDVHcybENKNDZnYXltYXd0RzZ6REZobldRCkxWdXhBcFQ1UlFhWUIrVnJteXQv
            YUR0ZG94c2tYZGpKVnhqeUZLMlc4TGMKLS0tIGhEdE5RQjJmN1dzM2lEdjluaUdC
            c0ZaQVJ5d0tpSFhMeWtORFF5cllLUTgKdf+VI21sABvKXkSIe38zNEWlEdVOOOAp
            5gGhK6u1z/fo1r8jjVqJT/QinxeoVNnzax6SR/qkwkY3lw4nW7wqNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T23:26:10Z"
    mac: ENC[AES256_GCM,data:Wu0dvIPKso6uMAI8p9wB8Wi0k1m+/yUm4byG7GXjmk0OXuth8oR0PZm4jRyfuH00NKBsZ9xXkt+efiyYfF/XGvA04UbHC0et+tuohACLk+I2ayV4QyuQS8aN/FR9KQ7lba7m0IsBxftKptKzTWEx6nOGb58QNo8H2YVtcMpRAFg=,iv:8IPG9/8zxQAB5Ogou28CqR6I/Qlg0qObmEgvKWVbWTs=,tag:JUwZTSKhwKo2KUPVnztJtw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
