apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:oqRT4N050jCy9Ip4ncxGwFVw+3Evx3/0qR1/WuH8GtbeAuIB8vjbrYwXr3ZN//Vlu1G50B6REjGl8+3zRVcKXK8GrakYWnOhi74SjAVGRkkxEh446pRC7+0hH19778JrcRsSdP44v/ZUtxzXK97r9OizhBbm43KhiQ==,iv:jSpr62r9kA4rZsA+G4VZxgM9/ASszDyW6EHI8GHTuGM=,tag:yu/e0byYvPGpElNw8T/GNw==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:als9n3RDAKFD7554t7pZGaPERTmzFsbksLyqCLlYNXDWVXCiPuhCtH8XB/XfZZeoRAtmkeRtWQtG1XBNukhAsw==,iv:v1U/2mP/iZyyLwidjlDD3/DlucTX9YUyp8zVwnjTD88=,tag:L5EoSqC84WOZtwrAjXxDoA==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:Tp7/TT7kgQ7OxV1ZZ0FxH5gHDZkBmsQ5v9ISn+rlFntOSO3nMFGwjRM7DX+yUuTYwXJoS3E5D0r4iKIVkcb28QaGtVJTY3rKcynAWhUZSbUipV5n/IwtgrLZVv+Y,iv:oqDq3ILi+l1Bz6igGEwICOsExXyT+xnS5j9sr3Le+I4=,tag:DqCiO/ifsK9+z3Aik59INg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRDY2cUhwTUVreE44Sk9m
            bStTblFFZUR3SHpiUVFxc0Y5aGZROHVNRjNrCmN1c0lFZnFjWmkxWXQ4Z2U4cXN2
            KzA4ZnFsRWdXTGNTMFN5Q2NQUGhSUmcKLS0tIGl1RmNzLzRWb1l4MnhLenArUW10
            ZE9XSGlmMllJL3hFTDQzc1VSRzR5OGcKrvqI783sOAjG0zd2fln/U4/7R6rCmEQX
            5hmHEYzO5L+SP2qhyhfIKMYFeLEstJZgOfOoyJu+LxFjeqDxJ0gQEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T23:56:16Z"
    mac: ENC[AES256_GCM,data:kHKITo0lvADqtsF8SWrg8FH2mdEO0ECoVGeThuD4GE+OmJ1sLSrmdwgh0HJDvAlvf9bah4LaSUAnj718AxPGLpbcga/bZtttKPMaI3u5UmRS/Z23RPdHqWLe+00Nr/9SAZ5k1ARohzy2F3DTwVDBzp5VjU48JqCO+GScKrQKIkE=,iv:eJBXKiUsmlUG6t7xd1YJlnefPpjH9Kv8E+E1m7Awh94=,tag:ROVYVHxmdqajZyFFJthKaA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
