apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:758gQ75rBYqfL6tZ6XJbAIpdeChVFSQeWVTWNyJFEBJBMY8WygUK587j9jZPI9JPMsRZDuGH6GmIkRmEV/ZF1uWX2Ka4wQ/zEEvyQp908fFvMRCaNeoFra/FLNklkxdmYgVbNDjAoE8sCJ7+XiYaz+s79JHyb6Hrxg==,iv:r41I760ZfB54ujiBIGgfBQzs1XXB4csZMCh2XOxWyKo=,tag:oP+zt+Nzca5eFHkvDiW5qA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWGlZL3NpeG80TWFFRUtq
            U283UHdXSEtCZllodmsreTVxZUdmYlJ4WEZzClpaajJXS0l5cW8wdEJORmZzQmhH
            RHF1dDFCRkVWTDF1WGM0N25PZ2FJWjQKLS0tIDdNaDJEd1BLR2k2SmNpV1JaQVd4
            bS9uUnIvZGRXV1lqekVmQkJmdng3bG8KlzQzZETIYnehbKoInkBnCNvibbWzOYIC
            eoJA0QGcxaIo9VUCKoriDAPNpg8Iw20EleWG1Rave11vHhHRJOqxfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T01:46:41Z"
    mac: ENC[AES256_GCM,data:3T4DWdaBFyiM+LOhxPsmiagDxxOXM7QeAVCqpDTGvsoIRpUdWSdOPbmqcpqOnR6SevDGwajHEFwhCArMSlciTzDV4mJc7EW9z8KxJzYeayuaSYwfAhvlOtjOfyNF/9qF5d7X4AYv2TXuJ92upy9GI+/SfnonPqLu4iEEkpoF7IM=,iv:oQsnK4qKYvvjl5OqMx3i0qkHSPXY/gEVEqDsbFXIVdM=,tag:b7fEuFNNDpqCjSb4heE8kA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
