apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:wi5AOmIf854PPLSy0QsPFqzkuVFHFqtiSgT+R8PB6nuamYK4IHFIOr3mqiBf2qhhdartw5B/5j92LnVWL51ELeAYAkAXsfMvpqk+ZEntrFZx4+K2BDjHV+60QKB2EWeadQXbNvIgrrVCbSWBX+PzRbGbfR51YtBtBg==,iv:J/uam+RLd8an8ptxhfjCcGKcufhY7SogMukOIBRcfzE=,tag:mx8TeCMe4stEogqrV4mKTg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlYXNERGRGNGZHY3UvMlpN
            MXQ3amdmYXMrd0lhd05BRG9nQ1pKUG5FQ0JnCjhNMHdzMDFzUEZmcFJVQWR3MVlw
            Vk5vYjl5eUZFS2VRUFFtVkNkR1B1V1kKLS0tIDY4YU5aaEJ2eUUydVpjQm9xTTFk
            YTJKUXJ1QWZSRi9vS09BYWV2SW1Ma3MK+XyOBhh7GSO7YGhFWHjCCh+4Kx3V9I5y
            QkMlfP8upY0Fv1PbjVFRDDfKHAWiGNj9gyiwxGQd2sLWqdL368HDLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T20:26:03Z"
    mac: ENC[AES256_GCM,data:oi0BovJ6XsoaxG2KaVleBcxV1yYe0EiLXH4eIait4vKHWLkE5Na2QDzjPX8CXje6AQwMxdz0jJTI4/Kvl61tCs9CIZZurt5s1L/BZTFo7/iUxfN7xbjh/CSFA0hbS282kd9ZdR67DzvgLUM4lJNdHAP9MAyyLm5j+RBNPs6CX3U=,iv:vswKz4ZezAVWkQOS+gpOYjxdrWovzpcTrPflqoPF4jM=,tag:DY0IqMti+Z1zTCbkF/Y5wQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
