apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:9409HoGcxxGZZQAW0+1amiI9E4PFUbA9o8GVA7VsOxRRdQa63Hzc5JPIQaCJnLMr2BdM4q5pn+PANI5TbuAxibmQrW9wWyKUFP+V5dj5lmU6o5cx3175BVEqDAuObQbsm4IDUacZST54Hre1aZ2lX2Xmqfe+3dcdTA==,iv:4V98L+WbZV3m6cWyR8kIxv9E1BgsIRZFz2VxSkBQn/g=,tag:LwswLzK8qO4+91/kF9W4xQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZOXJTSGFBM3N4cWcyR3py
            NkZrdXd5T1JsOFNPK3EvN1VuTUdkRFpOOTJzCitsSGo2REZmY2RKbWZOTnZtMHUv
            YWRzTk5KWC84SUJHN1ZETlMzUVI2ZGsKLS0tIGpYU3VaOTFZNnhwOXNxanFCTHRu
            YnEyVVdnak9SUXRRcWtCcDh3RFE0YjgKMVh4sYEys1a/2bOfa/e4lLluJ1L1LDca
            ZH1eOXaBxcGOZsmT7m4R+QWd97/itngHylAI02cIakP8MFJAXsjXXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T21:53:12Z"
    mac: ENC[AES256_GCM,data:MLkt4LTt5NJrkgpZzzituKDlZrseZ7gMUIZaBV5fwgRVv91csAfuIeE4Cnu9OmaGLxRz1Gmt/8cYqEj5vhMbjf2t/tpyVDDMTvpA8Gv2hCFWKWN3igo+HYKwuSFNO4VeU/Ip0oTMfsYn/Ip0BkmNgZW+TZaYXW8jZiXaK6gsIt8=,iv:WxtRBpDCxsyEnpD78p0YqBz916CPMU547Me9ZGDUfLQ=,tag:Zkxme2EUFycaoFKBaKo45Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
