apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:E9f6KMSthRyGL7gNlHr4TM6bcq8Dnw8SBbZbhMukprbCdjKPxq61OUJHGBDnrvLRdyxwkdMyEvq0tPxXjfpphpqXITirVUUgReSz2+Kr04P513jGHtw2EfrZAOcLdtdU5EhUKCupC7LTuZvOTxbsNKex+zTnv0Ls0g==,iv:32qLNytyM4Ofl3cHKAjFVgup2rFAcpIXz+CYYf9uXZw=,tag:2DosaI5NW06HVTIY/IA7Vw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQK044cG5SSkdkK1RhOUpP
            dDgvZFFadlBCL1M1VXA1ZDNFcGZBVVZTY1RNCm8wckJWV3ptZ2FCWkxlUTd6NXg1
            WUZkYjhHaFZrcTNtWVhiTG5TaGdtRGMKLS0tIExVbVhaMHlWbjY3Q2hINmtSMjRJ
            VXUyTW95K3VLaHhKM1llUlp2RVBzYzAKpkVcyyUA88Vt46PbDGGciJtUq651MOih
            LGQQW7sEN3Q6lrOSpDxzGUXMGK452SPXzyi90fippESRTUSw0Kb7qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T03:39:41Z"
    mac: ENC[AES256_GCM,data:aqcp0tufnyMxrz+Mx2mjv5UjSHXauJT1qiNc1j2cNwPAHi1wvAdFtWmL/2CsV1MSMd3FFd7jEIXIkBslyg5jHB7FkIAkxr8qzcOPfkl6Nbj680sAtu4z/tLieBvFURFxijhEak2Dwgo3JS3fwlcnwu3LrUcwf4JpmZsXJfFaLX8=,iv:oE9VeEzw24JZivcxdUHUrp5Jx2RkzZIo7EDQ2qq6qQA=,tag:tYJFvz0nUNzbl5lI3mJVCw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
