apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:5CQ5SuK7El3lGvwQZ5uUNXNAM6gNBSDEAJtzghMEUAGrTqhd/1XgVHdnZzun4yiJNJgKFIdCWIo4jF5zfbuIqWX8aGKy3RraFkzBr7Kt9uPUkD/Cebm4hKJpnxTFsG4xKh2M/6rYmm1ZfVusvbOXYx0JK2SUE2FEmw==,iv:hg/u4Qfc2nvXZABTBRcUoEPgETU3flAsVEzHtDPC+UE=,tag:ocZjqUWGgCxLtEgx26oLTg==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:jmQ+B4kd/Vbj0Hv3sXVFctdckxgx+6h+avfGpj6/k3WzZ1HgN9v9VTITc5x3L2AMa9PpcC4fQYy5LyzIS1QjoQ==,iv:hbDEPjxijnB0PqWC1aQrDf3+ONpi1zgFzBVzJ2a2Iuw=,tag:H0muA4AecoeEwK+iTKH/lg==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:oR+FLC8G6gZMjL7+yhrXNhyoPAvy8yaA3e731uWKev2pEsr9XOJY3YQU9+oc/UL32Ktsq/W7ODg0WPG3qFY2SvQyQ3f/hWQxM+7npiuYyNTgIpK5pnSE3ZwjTaNt,iv:W2bIfkXXQXQQdoicoF0+Ow4wcDxZbR5ncx4zfPzVq0A=,tag:gMCuADR/sbFKZzdKCw4O+g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJb0dSUW5UWVJVVGNFSW9x
            eXordHRuZ0Q5WjdKcVNWVS9Vc2xMQUNJczNBCnhZRHFIL25PNGgyU3k0VTNvQ08y
            TEJVUVZPK01HMExWL1ZnaHlNT2pMamsKLS0tICtkN2IzdXJ2aXdNNStMUTEzMU5B
            MDBCSUF5K2NQa2FKUnhwWGpWdGxKaDgKZ+ZuX4nOVYtmzn1Gz64J5aYO2DchoQPy
            IEUrpD09+bhaW3XwIFN1bLzBD2a3veseYqvRKCDoMxj73lUJfdnh8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T15:49:57Z"
    mac: ENC[AES256_GCM,data:zSTYgrQum5Muak+rZ0KxLkJTuGyXGTCa2Z1pzEUboUNVDzCOoFePj7rb5bCmUWTcqmR8QOP4Kt3dMWw2uy3NUb1eh6wC/jfyvEFMBTAlkaiS+Zl45f21op9spmwhH0QDKoDInjvzLpdbivbnGeMLLKLKI4W6oO9Au4sNqEDnS3w=,iv:FzAzTob507K68fXGBzwvCBWawa8uM378HgFA8EqX/RE=,tag:G2sT2I1yPwsRBAtX3YyhDw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
