apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:QBX6D4vKxYYB9cZZTk4sYNRTQB8L6EBR0uBTOgs70jbBBAikLNLQhKTIwWtwkgx3jMSAo7uDF2I/dS7Dpnj8+pey2QfqS4hAOs2wwfGhhpLB+e9UkHjTPuHU67k1Y9nAz/m4H/7u1Cuhwtg3Fh7l801pJyQzCyNp7g==,iv:EX9LwAY4YqY1oJk2sN6slY2Qzl1OIArdFLcC6+u/WrA=,tag:eOmzPzfi5Gms8niK6EfHKA==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:cLzrwoNkGlvwRFUfgv8H/qgasZBgupzn/9btxvJ8DWn/nWNfyIWXhkq+idjbgk5pSNbZfGuANast4E8EcRLHwA==,iv:SGIp7k/ESQ7/DlpIseWDyC1bTW4+Y9v2SyowXj3iiI8=,tag:mfddsKQpKf+629aKa7aqdA==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:aEbbxP/EvqpngSxwcV23DM1aXtqlwizpaYTPYl8hm7OLvNNPgBDNdvG4BEYgf9vCudBXQpjEMvVsf/PeBsfcJH2CXHs/2hZ+RqS/4k5inD9QTjMivw==,iv:kviKBmD9MjnslBmdA57ZaOqYPpjFg3QelphzFPf7i0o=,tag:jZ9IjWHkx4peVSSDNnjFbQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xr3zztpafgxmfj0lmwy60su76kwvxgpqdreyax0u2aa99qaftpvsfggls6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWXc4alF5SFFCUWk5enYx
            NkNMWElvcGsxRStSVkVnWUhkZXpWaFNGcjBjCnlKQlVsZHpBdnVhODlhNTQ4NEgx
            WFRVMk94VWpXV0RFMDY3ZVRrSUltWE0KLS0tIHlFblBKSk9yNG5OVDQ0T3N5T0Rz
            QXdxd0NZMjFxallldDNYeDFvdVphNHMKRzsgAM5FPk+QXCLtN4RjcY85YMea51y+
            x0mbJ8x78UyLSJE6yHz/Ob/Gc6wd9Je3qlBCmC1wScCDNA93zvSaMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T06:43:34Z"
    mac: ENC[AES256_GCM,data:TFDyOF0APXxoUYo9JgOCJ6i0IOMFdAXTq6M/iPCMhHZJYFHafL3KaVRip6mAf5mawJIm/hGc5t8VQHHeKu6ygG1wmbzMUnMCvowMQ6fAEIOV3SjXoHKuY/MqulLyiyiaGNCbU5qM48YhqOsDzBoRnH5zXd3QgeEcB+hsFHe4Ogk=,iv:Bw+lWgUjjtjd2l6XG+DA8UHFvdbMwKzy3c/BMb3R7Ow=,tag:op2PuiluCvITTPuLHjPrcA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
